"""
equipment/validation.py — the ordered physical validation workflow (SFSU equipment only).

Single source for docs/rev2/BENCH_CHECKLIST.md (generated by tools/gen_rev2_docs.py).
Roles: EDU36311A = low-energy commissioning source; EDU34450A = reference DMM;
EDUX1052G = transient/shutdown observation; AD2 = low-voltage digital/protocol
debugging; 6060B = the actual battery load (manual until GPIB is confirmed).

Every step starts NOT_RUN. This module never sets BENCH_TESTED or
HARDWARE_VALIDATED — those are judgements for a person with recorded data.
Acceptance tolerances are NOT invented here: the operator writes the tolerance
into the record BEFORE the run (no accuracy claim exists until then).
"""

import json
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime

NOT_RUN, PASS, FAIL, BLOCKED = "NOT_RUN", "PASS", "FAIL", "BLOCKED"
STATUSES = (NOT_RUN, PASS, FAIL, BLOCKED)


@dataclass(frozen=True)
class Step:
    id: str
    phase: str
    title: str
    equipment: str
    procedure: str
    pass_criterion: str
    blocked_by: str = ""


STEPS = [
    # ── A: records and inspection ──────────────────────────────────────
    Step("A1", "A. Records", "Record identity of every instrument",
         "all instruments",
         "Read model, serial, asset ID and calibration-due date off each instrument "
         "(6060B, EDU34450A, EDU36311A, EDUX1052G, EDU33212A, AD2, handheld DMM). Enter in equipment/inventory.py.",
         "No asset ID or calibration status left UNKNOWN for an instrument used as a reference."),
    Step("A2", "A. Records", "Inspect the OSBAMS power path and wiring",
         "handheld DMM",
         "Read the exact Durakool DG57CM part number, shunt part number, fuse and fuse-holder part numbers, and the 12->5 V DC/DC converter(s) "
         "(the four open items in HARDWARE_FREEZE_CANDIDATE.md); check polarity labelling, wire gauge, connector type and that the shunt is in series. "
         "Continuity and polarity with the handheld DMM, power OFF, no source connected.",
         "Every power-path rating written into capability.PowerPathLimits or marked unspecified."),
    # ── B: low-energy commissioning (no battery, no 6060B) ──────────────
    Step("B1", "B. Low-energy commissioning", "Controller, I2C and UART bring-up",
         "AD2 (logic/UART/I2C), USB power only",
         "Power the STM32 board from USB. Capture I2C: INA228 and TC74 acknowledge at their addresses. "
         "Capture UART: Protocol v1 frames decode and CRC-validate (also feed a captured line to services.protocol.parse_frame).",
         "Both sensors ACK; frames parse with valid CRC; sequence numbers increment."),
    Step("B2", "B. Low-energy commissioning", "INA228 voltage accuracy",
         "EDU36311A (CH2, and CH2+CH3 in series per the manufacturer's series-operation instructions), EDU34450A",
         "Step 3, 5, 10, 20, 30 V (and higher via series only after reading the EDU36311A manual). At each step record "
         "EDU34450A and OSBAMS voltage with equipment.reference.make_record('voltage', ...).",
         "Records saved; error shown per point; tolerance written beforehand by the operator.", "A1"),
    Step("B3", "B. Low-energy commissioning", "INA228 current accuracy at low current",
         "EDU36311A (CH1 into a resistor), EDU34450A in series (check its current range/fuse first)",
         "Drive 0.1, 0.25, 0.5, 1.0 A through the shunt. Record reference vs OSBAMS current.",
         "Records saved; error vs current plotted; decide if the existing shunt is adequate at 1-3 A.", "B2"),
    Step("B4", "B. Low-energy commissioning", "Temperature sensor check",
         "EDU34450A (temperature function), TC74",
         "Compare ambient and a warmed point (hand/warm water bath, not a battery).",
         "Records saved; 1 C TC74 resolution acknowledged in the result.", "A1"),
    Step("B5", "B. Low-energy commissioning", "ADC divider cross-check and disagreement fault",
         "EDU36311A, EDU34450A",
         "Compare INA228 vs ADC voltage over 5-30 V; inject a deliberate divider error and confirm the disagreement fault fires.",
         "Fault raised at the injected error; no false fault over the normal range.", "B2"),
    Step("B6", "B. Low-energy commissioning", "Threshold and fault-injection tests",
         "EDU36311A, EDU33212A (sensor-signal injection), AD2",
         "Drive over-voltage, under-voltage, over-temperature (simulated sensor value), sensor loss, host disconnect.",
         "Firmware reaches FAULT in each case and the load-enable output goes OFF.", "B1"),
    Step("B7", "B. Low-energy commissioning", "Contactor and E-stop timing",
         "EDUX1052G, EDU36311A (low-voltage supply through the contactor into a resistor)",
         "Capture coil drive, aux feedback (PC9) and downstream voltage. Measure close time, open time and E-stop-to-open "
         "with the MCU held in reset. Repeat >= 10 times. Probe only with rated probes and good grounding.",
         "Times recorded; contactor opens on E-stop with the firmware dead.", "B1"),
    # ── C: 6060B without a battery ──────────────────────────────────────
    Step("C1", "C. 6060B without a battery", "6060B power-up and front-panel record",
         "6060B (manual), handheld DMM",
         "Run the 6060B power-up self-test. Record the GPIB address setting, input range and protection settings. "
         "Use Manual6060B in OSBAMS.",
         "Self-test passes; settings recorded."),
    Step("C2", "C. 6060B without a battery", "Three-way comparison OSBAMS vs 6060B vs EDU34450A",
         "EDU36311A as the source, 6060B (manual, CC), EDU34450A, OSBAMS INA228",
         "At 3 voltage points <= 30 V and currents <= 1 A (supply limit), set CC on the 6060B panel. Record voltage and current "
         "from all three instruments.",
         "Records saved with 6060B readback and reference; discrepancies listed.", "B2, B3, C1"),
    Step("C3", "C. 6060B without a battery", "Software envelope vs panel setting",
         "Dashboard permitted-current panel, 6060B panel",
         "For 3 voltages read the FINAL PERMITTED value from the dashboard and confirm the operator-entered CC setting never exceeds it. "
         "Do NOT deliberately exceed 300 W on the instrument.",
         "Panel value = min(profile, 10 A, 60 A, 300 W / V) at each voltage.", "C1"),
    Step("C4", "C. 6060B without a battery", "Orchestrator dry run on a supply 'pack'",
         "EDU36311A CH2 as a stand-in source (NOT a battery), 6060B (manual), OSBAMS, dashboard",
         "Create a low-voltage registry row (e.g. 12 V, cutoff 9 V). Run the Capacity test: OCV -> READY -> operator enables load -> "
         "lower the supply voltage by hand to cross the cutoff -> verify automatic load-off request and recovery. Run DCIR (steps within the 1 A supply limit).",
         "All phases reached in order; load-off confirmed from measurement; results saved. A supply does not model a battery, so no capacity/DCIR number from this step is meaningful.", "C2, C3"),
    Step("C5", "C. 6060B without a battery", "E-stop / fault during a loaded run",
         "EDUX1052G, EDU36311A source, 6060B (manual)",
         "During C4 press the E-stop; capture current decay and observe the orchestrator report FAULT with verified load-off.",
         "Current falls to ~0; orchestrator ends FAULT/off-confirmed; times recorded.", "B7, C4"),
    # ── D: supervised battery tests ─────────────────────────────────────
    Step("D1", "D. Battery tests", "Intake and OCV of the first pack (Ninebot NEB1002-H, 5.2 Ah)",
         "handheld DMM (polarity), EDU34450A (OCV), OSBAMS",
         "Inspect, check polarity, measure OCV with the reference DMM, register with a cutoff voltage. Compare OSBAMS OCV.",
         "Registry row complete with cutoff; OCV agreement recorded.", "C5"),
    Step("D2", "D. Battery tests", "Orchestrated CC capacity test (NEB1002-H)",
         "6060B (manual CC <= the dashboard's FINAL PERMITTED, profile 1 A), OSBAMS, EDU34450A spot checks",
         "Run Capacity: OCV -> READY -> confirm -> discharge to the profile cutoff -> load OFF verified -> recovery. Spot-check voltage with the EDU34450A at start, mid and end.",
         "Automatic cutoff; load-off confirmed; Ah/Wh stored; V/I spot-checks recorded; temperature below limit.", "D1"),
    Step("D3", "D. Battery tests", "DCIR current-step test (NEB1002-H)",
         "6060B (manual), OSBAMS",
         "Run DCIR as a separate test on a rested pack; repeat 3 times with rest between.",
         "Three results recorded; repeatability reported (no tolerance claimed).", "D2"),
    Step("D4", "D. Battery tests", "Thermal observation",
         "EDU34450A temperature function, TC74",
         "During D2/D3 compare pack-surface temperature (reference) with TC74; record peak.",
         "Peak temperature recorded; stop-on-limit behaviour verified or marked untested. Thermal protection is NOT validated until the TC74 works and is attached at a suitable point.", "D2"),
    Step("D5", "D. Battery tests", "Repeat on Shenzhen Elite (12.8 Ah) then NEE1006-M (15.3 Ah)",
         "as D1-D4",
         "Same sequence. Packs with BMS anomalies in the intake notes (blinking blue, cut wire) are inspected and judged safe BEFORE any connection.",
         "Per-pack records saved; no pack connected without an inspection note.", "D3"),
    Step("D6", "D. Battery tests", "Passport and report reproducibility",
         "OSBAMS",
         "Generate the report for each pack, regenerate it, and compare.",
         "Reports identical except timestamps; version block present.", "D2"),
    # ── E: remote control (blocked) ─────────────────────────────────────
    Step("E1", "E. Remote control (blocked)", "Identify the SFSU GPIB path",
         "lab inventory",
         "USB<->GPIB adapter, LAN<->GPIB gateway or GPIB-equipped PC? Record models and the 6060B GPIB address "
         "(docs/rev2/GPIB_INTERFACE_CONFIRMATION.md).",
         "A concrete interface identified and recorded.", "A1"),
    Step("E2", "E. Remote control (blocked)", "Verify commands against the official manuals",
         "Electronic Load Family Programming Reference Manual; 6060B/6063B Operating Manual",
         "For each row of 6060B_COMMAND_EVIDENCE.md read the exact command, fill document + section/page, set VERIFIED.",
         "Operations are enabled only when every command they need is VERIFIED.", "E1"),
    Step("E3", "E. Remote control (blocked)", "First remote contact on a supply, no battery",
         "6060B + GPIB path, EDU36311A, EDU34450A",
         "Construct Keysight6060B(interface_confirmed=True); identify, set_cc, input_on/off, measure on a supply source; compare with EDU34450A.",
         "Readbacks agree with the reference; envelope guard refuses over-limit requests without writing.", "E2"),
    Step("E4", "E. Remote control (blocked)", "Transient observation",
         "6060B remote, EDUX1052G (current probe/shunt), AD2 optional",
         "Configure a low-amplitude transient on a supply source and observe the current step on the scope.",
         "Observed levels/frequency match the configuration.", "E3"),
]

STEP_BY_ID = {s.id: s for s in STEPS}


@dataclass
class StepRecord:
    step_id: str
    status: str = NOT_RUN
    operator: str = ""
    date: str = ""
    software_commit: str = ""
    tolerance_set_before_run: str = ""
    data_location: str = ""
    notes: str = ""


@dataclass
class ValidationLog:
    records: dict = field(default_factory=lambda: {s.id: StepRecord(s.id) for s in STEPS})

    def record(self, step_id: str, status: str, operator: str, **kw) -> StepRecord:
        if status not in STATUSES:
            raise ValueError(f"status must be one of {STATUSES}")
        step = STEP_BY_ID[step_id]
        if status == PASS:
            for dep in [d.strip() for d in step.blocked_by.split(",") if d.strip()]:
                if self.records[dep].status != PASS:
                    raise ValueError(f"{step_id} requires {dep} to be PASS first")
            if not operator or not kw.get("data_location"):
                raise ValueError("PASS needs an operator and a data_location (recorded data)")
        r = self.records[step_id]
        r.status, r.operator = status, operator
        r.date = kw.pop("date", datetime.now().isoformat(timespec="seconds"))
        for k, v in kw.items():
            setattr(r, k, v)
        return r

    def next_step(self):
        for s in STEPS:
            if self.records[s.id].status != PASS:
                return s
        return None

    def save(self, path: str) -> None:
        with open(path, "w") as f:
            json.dump({k: asdict(v) for k, v in self.records.items()}, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "ValidationLog":
        log = cls()
        if os.path.exists(path):
            for k, v in json.load(open(path)).items():
                log.records[k] = StepRecord(**v)
        return log
