"""
equipment/validation.py — the ordered physical validation workflow (SFSU equipment only).

Single source for docs/rev2/BENCH_CHECKLIST.md (generated by tools/gen_rev2_docs.py).
Order (user-specified): low-energy commissioning (EDU36311A / E3630A) -> voltage
calibration vs EDU34450A -> cross-check with HP 34401A -> current validation vs
6060B readback and DMM -> EDUX1052G contactor/fault timing -> AD2 UART/I2C
debugging -> dry run -> ONLY THEN a real 36-42 V lithium-ion pack.
EDU34450A / 34401A = reference DMMs; EDUX1052G (HP 54601B optional cross-check)
= timing; AD2 = protocol debug; 6060B = the actual battery load (manual until
GPIB is confirmed).

Every step starts NOT_RUN. This module never sets BENCH_TESTED or
HARDWARE_VALIDATED — those are judgements for a person with recorded data.
Acceptance tolerances are NOT invented here: the operator writes the tolerance
into the record BEFORE the run (no accuracy claim exists until then).
"""

import json
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime

NOT_RUN, PASS, FAIL, BLOCKED = "NOT_RUN", "PASS", "FAIL", "BLOCKED"
STATUSES = (NOT_RUN, PASS, FAIL, BLOCKED)


@dataclass(frozen=True)
class Step:
    id: str
    phase: str
    title: str
    equipment: str
    procedure: str
    pass_criterion: str
    blocked_by: str = ""
    optional: bool = False


STEPS = [
    # ── A: records and inspection ──────────────────────────────────────
    Step("A1", "A. Records", "Record identity of every instrument",
         "all instruments",
         "Read model, serial, asset ID and calibration-due date off each instrument (6060B, EDU34450A, HP 34401A, "
         "EDU36311A, HP E3630A, EDUX1052G, HP 54601B, EDU33212A, HP 33120A, AD2, handheld DMM). Enter in equipment/inventory.py.",
         "No asset ID or calibration status left UNKNOWN for an instrument used as a reference (EDU34450A, HP 34401A, 6060B)."),
    Step("A2", "A. Records", "Inspect the OSBAMS power path and wiring",
         "handheld DMM",
         "Read the exact Durakool DG57CM part number, shunt part number, fuse and fuse-holder part numbers, and the 12->5 V DC/DC converter(s) "
         "(the four open items in HARDWARE_FREEZE_CANDIDATE.md); check polarity labelling, wire gauge, connector type and that the shunt is in series. "
         "Continuity and polarity with the handheld DMM, power OFF, no source connected.",
         "Every power-path rating written into capability.PowerPathLimits or marked unspecified."),
    # ── B: safe low-energy commissioning ───────────────────────────────
    Step("B1", "B. Low-energy commissioning (EDU36311A / E3630A)", "Controller and sensor bring-up",
         "USB power only; EDU36311A or HP E3630A for any sensor supply",
         "Power the STM32 board from USB. Start the OSBAMS serial reader. Confirm INA228 and TC74 report and that Protocol v1 frames arrive with valid CRC "
         "and incrementing sequence numbers. If anything fails, go to G1 (AD2) to debug, then return here.",
         "Both sensors healthy in the BOOT/SENSOR frames; frames parse with valid CRC.", "A1"),
    Step("B2", "B. Low-energy commissioning (EDU36311A / E3630A)", "Fault-threshold and state-machine tests",
         "EDU36311A (primary) / HP E3630A (manual), EDU33212A or HP 33120A for sensor-signal injection",
         "Drive over-voltage, under-voltage, over-temperature (simulated sensor value), sensor loss and host disconnect at the "
         "profile thresholds, supply side only, no battery and no 6060B.",
         "Firmware reaches FAULT in each case and the load-enable output goes OFF.", "B1"),
    # ── C: voltage calibration against EDU34450A ───────────────────────
    Step("C1", "C. Voltage calibration (EDU34450A)", "INA228 voltage accuracy",
         "EDU36311A (CH2, and CH2+CH3 in series per the manufacturer's series-operation instructions), EDU34450A",
         "Step 3, 5, 10, 20, 30 V (higher only via series, after reading the EDU36311A manual) up to the 44 V ceiling region. At each point record EDU34450A and "
         "OSBAMS voltage with equipment.reference.make_record('voltage', ...).",
         "Records saved; error shown per point; tolerance written beforehand by the operator.", "B1"),
    Step("C2", "C. Voltage calibration (EDU34450A)", "ADC divider cross-check and disagreement fault",
         "EDU36311A, EDU34450A",
         "Compare INA228 vs ADC voltage over 5-30 V (and series up to the supply limit); inject a deliberate divider error and confirm the disagreement fault fires.",
         "Fault raised at the injected error; no false fault over the normal range.", "C1"),
    Step("C3", "C. Voltage calibration (EDU34450A)", "Temperature sensor check",
         "EDU34450A (temperature function), TC74",
         "Compare ambient and a warmed point (hand/warm water bath, not a battery). Thermal protection is NOT validated until the TC74 works and is attached at a suitable point.",
         "Records saved; 1 C TC74 resolution acknowledged in the result.", "A1"),
    # ── D: cross-check with HP 34401A ──────────────────────────────────
    Step("D1", "D. Cross-check (HP 34401A)", "EDU34450A vs HP 34401A",
         "EDU36311A as the source, EDU34450A, HP 34401A",
         "Measure the same stable voltage points (and a resistor) with both DMMs at once/alternately; record the difference with "
         "make_record(..., secondary=HP34401A, secondary_reading=...).",
         "Difference recorded per point; any disagreement larger than the tolerance set beforehand is resolved before continuing.", "C1"),
    Step("D2", "D. Cross-check (HP 34401A)", "OSBAMS voltage vs HP 34401A",
         "EDU36311A, HP 34401A, EDU34450A",
         "Repeat a subset of C1 points reading the HP 34401A as the independent check on the EDU34450A-calibrated OSBAMS channel.",
         "OSBAMS agrees with BOTH references within the tolerance set beforehand, or the discrepancy is explained.", "D1"),
    # ── E: current measurement ─────────────────────────────────────────
    Step("E0", "E. Current measurement and 6060B", "6060B power-up and front-panel record",
         "6060B (manual), handheld DMM",
         "Run the 6060B power-up self-test. Record the GPIB address setting, input range and protection settings. Use Manual6060B in OSBAMS.",
         "Self-test passes; settings recorded.", "A1"),
    Step("E1", "E. Current measurement and 6060B", "INA228 current accuracy at low current",
         "EDU36311A (CH1 into a resistor), EDU34450A in series (check its current range/fuse first), HP 34401A where practical",
         "Drive 0.1, 0.25, 0.5, 1.0 A through the shunt. Record reference vs OSBAMS current.",
         "Records saved; error vs current plotted; decide if the existing shunt is adequate at 1-3 A.", "C1"),
    Step("E2", "E. Current measurement and 6060B", "Three-way comparison OSBAMS vs 6060B vs DMM",
         "EDU36311A as the source, 6060B (manual, CC), EDU34450A, HP 34401A, OSBAMS INA228",
         "At 3 voltage points <= 30 V and currents <= 1 A (supply limit), set CC on the 6060B panel. Record voltage and current "
         "from OSBAMS, the 6060B panel readback and the DMM.",
         "Records saved with 6060B readback and reference; discrepancies listed.", "E0, E1, D2"),
    Step("E3", "E. Current measurement and 6060B", "Software envelope vs panel setting",
         "Dashboard permitted-current panel, 6060B panel",
         "For 3 voltages read FINAL PERMITTED from the dashboard and confirm the operator-entered CC setting never exceeds it. "
         "Do NOT deliberately exceed 300 W on the instrument.",
         "Panel value = min(profile, 10 A, 60 A, 300 W / conservative V) at each voltage.", "E0"),
    # ── F: EDUX1052G timing ────────────────────────────────────────────
    Step("F1", "F. Timing (EDUX1052G)", "Contactor / load-enable timing",
         "EDUX1052G, EDU36311A (low-voltage supply through the contactor into a resistor)",
         "Capture load-enable (PC8), coil drive, aux feedback (PC9) and downstream voltage. Measure close and open time, >= 10 repetitions. "
         "Rated probes and good grounding only.",
         "Times recorded.", "B1"),
    Step("F2", "F. Timing (EDUX1052G)", "Fault-shutdown and E-stop timing",
         "EDUX1052G, EDU36311A",
         "Trigger a firmware fault and the E-stop; measure fault-to-open and E-stop-to-open time. Repeat with the MCU held in reset for the E-stop.",
         "Times recorded; the contactor opens on E-stop with the firmware dead.", "F1"),
    Step("F3", "F. Timing (EDUX1052G)", "Cross-check timing on the HP 54601B (optional)",
         "HP 54601B (secondary scope), EDUX1052G",
         "Repeat one F1 capture on both scopes.",
         "Times agree within the tolerance set beforehand.", "F1", optional=True),
    # ── G: AD2 protocol debugging ──────────────────────────────────────
    Step("G1", "G. Protocol debugging (AD2)", "UART / I2C capture",
         "Analog Discovery 2 (logic analysis, UART/I2C decode)",
         "Capture I2C: INA228 and TC74 acknowledge at their addresses. Capture UART: Protocol v1 frames decode and CRC-validate "
         "(feed a captured line to services.protocol.parse_frame). Use for debugging any B1 failure.",
         "Both sensors ACK; captured frames parse with valid CRC.", "B1"),
    # ── H: dry run on a supply ─────────────────────────────────────────
    Step("H1", "H. Orchestrator dry run (no battery)", "Orchestrator dry run on a supply 'pack'",
         "EDU36311A CH2 as a stand-in source (NOT a battery), 6060B (manual), OSBAMS, dashboard",
         "Create a low-voltage lithium-ion-style registry row within the supply limits (e.g. 12 V nominal, cutoff 9 V — a software dry run only, not a supported pack). "
         "Run Capacity: OCV -> safety check -> READY -> operator enables load -> lower the supply by hand through the cutoff -> verify automatic load-off request and recovery. Then DCIR.",
         "All phases in order; load-off confirmed from measurement; safety checks logged. A supply does not model a battery, so no capacity/DCIR number is meaningful.",
         "E2, E3, F2, G1"),
    Step("H2", "H. Orchestrator dry run (no battery)", "E-stop / fault during a loaded run",
         "EDUX1052G, EDU36311A source, 6060B (manual)",
         "During H1 press the E-stop; capture current decay and observe the orchestrator report FAULT with verified load-off.",
         "Current falls to ~0; orchestrator ends FAULT/off-confirmed; times recorded.", "H1"),
    # ── I: real 36-42 V packs ──────────────────────────────────────────
    Step("I1", "I. Real 36-42 V lithium-ion packs", "Intake and OCV of the first pack (Ninebot NEB1002-H, 5.2 Ah)",
         "handheld DMM (polarity), EDU34450A (OCV), HP 34401A (cross-check), OSBAMS",
         "Gate: every earlier non-optional step PASS. Inspect, check polarity, measure OCV with both DMMs, register with chemistry and a cutoff voltage. Compare OSBAMS OCV.",
         "Registry row complete (chemistry, cutoff); OCV agreement recorded.", "A2, B2, C2, C3, D2, E2, E3, F2, G1, H2"),
    Step("I2", "I. Real 36-42 V lithium-ion packs", "Orchestrated CC capacity test (NEB1002-H)",
         "6060B (manual CC <= the dashboard's FINAL PERMITTED, profile 1 A), OSBAMS, EDU34450A spot checks",
         "Run Capacity: OCV -> safety check -> READY -> confirm -> discharge to the profile cutoff -> load OFF verified -> recovery. Spot-check voltage with the EDU34450A at start, mid and end.",
         "Automatic cutoff; load-off confirmed; Ah/Wh stored; V/I spot-checks recorded; temperature below limit.", "I1"),
    Step("I3", "I. Real 36-42 V lithium-ion packs", "DCIR current-step test (NEB1002-H)",
         "6060B (manual), OSBAMS",
         "Run DCIR as a separate test on a rested pack; repeat 3 times with rest between.",
         "Three results recorded; repeatability reported (no tolerance claimed).", "I2"),
    Step("I4", "I. Real 36-42 V lithium-ion packs", "Thermal observation",
         "EDU34450A temperature function, TC74",
         "During I2/I3 compare pack-surface temperature (reference) with TC74; record peak.",
         "Peak temperature recorded; stop-on-limit behaviour verified or marked untested.", "I2"),
    Step("I5", "I. Real 36-42 V lithium-ion packs", "Repeat on Shenzhen Elite (12.8 Ah) then NEE1006-M (15.3 Ah)",
         "as I1-I4",
         "Same sequence. Packs with BMS anomalies in the intake notes (blinking blue, cut wire) are inspected and judged safe BEFORE any connection.",
         "Per-pack records saved; no pack connected without an inspection note.", "I3"),
    Step("I6", "I. Real 36-42 V lithium-ion packs", "Passport and report reproducibility",
         "OSBAMS",
         "Generate the report for each pack, regenerate it, and compare.",
         "Reports identical except timestamps; version block present.", "I2"),
    # ── J: remote control (blocked) ────────────────────────────────────
    Step("J1", "J. Remote control (blocked)", "Identify the SFSU GPIB path",
         "lab inventory",
         "USB<->GPIB adapter, LAN<->GPIB gateway or GPIB-equipped PC? Record models and the 6060B GPIB address "
         "(docs/rev2/GPIB_INTERFACE_CONFIRMATION.md).",
         "A concrete interface identified and recorded.", "A1"),
    Step("J2", "J. Remote control (blocked)", "Verify commands against the official manuals",
         "Electronic Load Family Programming Reference Manual; 6060B/6063B Operating Manual",
         "For each row of 6060B_DRIVER_EVIDENCE.md read the exact command, fill document + section/page, set VERIFIED.",
         "Operations are enabled only when every command they need is VERIFIED.", "J1"),
    Step("J3", "J. Remote control (blocked)", "First remote contact on a supply, no battery",
         "6060B + GPIB path, EDU36311A, EDU34450A",
         "Construct Keysight6060B(interface_confirmed=True); identify, set_cc, input_on/off, measure on a supply source; compare with EDU34450A.",
         "Readbacks agree with the reference; envelope guard refuses over-limit requests without writing.", "J2"),
    Step("J4", "J. Remote control (blocked)", "Transient observation",
         "6060B remote, EDUX1052G (current probe/shunt)",
         "Only if the transient commands are VERIFIED: configure a low-amplitude transient on a supply source and observe the current step on the scope.",
         "Observed levels/frequency match the configuration.", "J3"),
]

STEP_BY_ID = {s.id: s for s in STEPS}


@dataclass
class StepRecord:
    step_id: str
    status: str = NOT_RUN
    operator: str = ""
    date: str = ""
    software_commit: str = ""
    tolerance_set_before_run: str = ""
    data_location: str = ""
    notes: str = ""


@dataclass
class ValidationLog:
    records: dict = field(default_factory=lambda: {s.id: StepRecord(s.id) for s in STEPS})

    def record(self, step_id: str, status: str, operator: str, **kw) -> StepRecord:
        if status not in STATUSES:
            raise ValueError(f"status must be one of {STATUSES}")
        step = STEP_BY_ID[step_id]
        if status == PASS:
            for dep in [d.strip() for d in step.blocked_by.split(",") if d.strip()]:
                if self.records[dep].status != PASS and not STEP_BY_ID[dep].optional:
                    raise ValueError(f"{step_id} requires {dep} to be PASS first")
            if not operator or not kw.get("data_location"):
                raise ValueError("PASS needs an operator and a data_location (recorded data)")
        r = self.records[step_id]
        r.status, r.operator = status, operator
        r.date = kw.pop("date", datetime.now().isoformat(timespec="seconds"))
        for k, v in kw.items():
            setattr(r, k, v)
        return r

    def next_step(self):
        for s in STEPS:
            if self.records[s.id].status != PASS and not s.optional:
                return s
        return None

    def save(self, path: str) -> None:
        with open(path, "w") as f:
            json.dump({k: asdict(v) for k, v in self.records.items()}, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "ValidationLog":
        log = cls()
        if os.path.exists(path):
            for k, v in json.load(open(path)).items():
                log.records[k] = StepRecord(**v)
        return log
