"""
equipment/validation.py — the ordered physical validation workflow.

Single source for docs/rev2/BENCH_CHECKLIST.md (generated by tools/gen_rev2_docs.py).
Equipment: the 6060B (the actual battery load, manual until GPIB is confirmed),
the EDU34450A (reference measurement) and the EDUX1052G (validation-only
observation), plus the OSBAMS stack itself. Nothing else is assumed.

Order: records -> bench bring-up with no battery -> pack connected, relay open,
no load -> first supervised low-current load -> full characterization.

Every step starts NOT_RUN. This module never sets BENCH_TESTED or
HARDWARE_VALIDATED — those are judgements for a person with recorded data.
Acceptance tolerances are NOT invented here: the operator writes the tolerance
into the record BEFORE the run (no accuracy claim exists until then).
"""

import json
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime

NOT_RUN, PASS, FAIL, BLOCKED = "NOT_RUN", "PASS", "FAIL", "BLOCKED"
STATUSES = (NOT_RUN, PASS, FAIL, BLOCKED)


@dataclass(frozen=True)
class Step:
    id: str
    phase: str
    title: str
    equipment: str
    procedure: str
    pass_criterion: str
    blocked_by: str = ""
    optional: bool = False


STEPS = [
    # ── A: records and inspection ──────────────────────────────────────
    Step("A1", "A. Records", "Record identity of the reference instruments",
         "6060B, EDU34450A, EDUX1052G",
         "Read model, serial, asset ID and calibration-due date off each instrument. Enter them in equipment/inventory.py.",
         "No asset ID or calibration status left UNKNOWN for the 6060B or the EDU34450A."),
    Step("A2", "A. Records", "Inspect the OSBAMS power path and wiring",
         "EDU34450A (continuity / resistance)",
         "Fill in docs/rev2/HARDWARE_ACCEPTANCE_RECORD.md: read the exact relay part number (firmware records Durakool DG57CM-5021-76-1012-R), shunt, fuse and fuse-holder part numbers and the 12->5 V DC/DC converter(s) off the installed parts. "
         "Check polarity labelling, wire gauge, XT60 connector and that the shunt is in series. "
         "Continuity and polarity with the EDU34450A, power OFF, nothing connected.",
         "Every power-path rating written into capability.PowerPathLimits or marked unspecified.", "A1"),
    # ── B: bench bring-up, no battery ──────────────────────────────────
    Step("B1", "B. Bench bring-up (no battery)", "Controller and sensor bring-up",
         "STM32L476RG on USB power, Raspberry Pi 5 / PC running OSBAMS",
         "Power the STM32 board from USB. Start the OSBAMS serial reader. Confirm INA228 and TC74 report and that Protocol v1 frames "
         "arrive with valid CRC and incrementing sequence numbers.",
         "Both sensors healthy in the BOOT/SENSOR frames; frames parse with valid CRC.", "A1"),
    Step("B2", "B. Bench bring-up (no battery)", "Fault handling that needs no source",
         "OSBAMS only (no battery, no load)",
         "Unplug a sensor; unplug the host link; press the E-stop; exercise relay feedback; trigger over-temperature by lowering the "
         "temperature limit and warming the TC74; trigger over-voltage by setting a profile maximum below a measured value.",
         "Firmware reaches FAULT in each case and the load-enable output goes OFF.", "B1"),
    Step("B3", "B. Bench bring-up (no battery)", "Relay coil-side timing",
         "EDUX1052G (rated probes, good grounding)",
         "Capture load-enable (PC8), coil drive and aux feedback (PC9). Measure close and open time and E-stop-to-coil-open with the MCU held in reset; >= 10 repetitions. "
         "No battery voltage on the relay contacts.",
         "Times recorded; the coil de-energises on E-stop with the firmware dead.", "B1"),
    # ── C: pack connected, relay open, no load ─────────────────────────
    Step("C1", "C. Pack connected, relay open, no load", "First pack connection and OCV verification (Ninebot NEB1002-H, 5.2 Ah)",
         "EDU34450A (polarity before connecting, then OCV), OSBAMS",
         "Gate: A2, B2, B3 PASS. Inspect the pack, check polarity with the EDU34450A, connect with the relay OPEN and no load. "
         "Compare OSBAMS INA228 voltage with the EDU34450A and record with equipment.reference.make_record('voltage', ...).",
         "Record saved; error shown; tolerance written beforehand. Registry row complete (chemistry, cutoff).", "A2, B2, B3"),
    Step("C2", "C. Pack connected, relay open, no load", "Independent ADC cross-check",
         "EDU34450A",
         "Compare the independent ADC voltage with the INA228 and the EDU34450A at the same moment. Confirm the disagreement fault fires "
         "when the threshold is deliberately set below the measured difference (test configuration).",
         "Fault raised at the injected threshold; no false fault at the normal threshold.", "C1"),
    Step("C3", "C. Pack connected, relay open, no load", "Temperature sensor check",
         "EDU34450A (temperature function), TC74",
         "Compare ambient with the EDU34450A. Thermal protection is NOT validated until the TC74 works and is attached at a suitable point on the pack.",
         "Record saved; 1 C TC74 resolution acknowledged.", "C1"),
    Step("C4", "C. Pack connected, relay open, no load", "Software envelope vs the 6060B panel",
         "Dashboard permitted-current panel, 6060B front panel",
         "With the pack voltage shown, read FINAL PERMITTED and the limiting factor. Confirm it equals min(profile, 10 A, 60 A, 300 W / conservative V). "
         "Load input stays OFF. Do NOT deliberately exceed 300 W on the instrument.",
         "Panel value matches the formula at the measured pack voltage.", "C1"),
    # ── D: first supervised load, low current ──────────────────────────
    Step("D1", "D. First supervised load (low current)", "Low-current measurement comparison",
         "6060B (manual CC, <= 0.5 A and <= FINAL PERMITTED), EDU34450A in series (check its current range/fuse first), OSBAMS, EDUX1052G",
         "Gate: C2, C3, C4 PASS. Close the relay, set CC on the 6060B panel and enable the load. Record current from OSBAMS, the 6060B panel and the EDU34450A at "
         "0.1, 0.25 and 0.5 A, and voltage spot checks. Capture load-enable-to-current onset.",
         "Records saved with 6060B readback and reference; discrepancies listed; decide if the existing shunt is adequate at 1-3 A.", "C2, C3, C4"),
    Step("D2", "D. First supervised load (low current)", "E-stop and shutdown timing under load",
         "6060B (manual), EDUX1052G",
         "At <= 0.5 A press the E-stop and trigger a firmware fault; measure fault-to-current-zero and E-stop-to-open; observe voltage transients.",
         "Times recorded; load current reaches ~0; no unexpected transient.", "D1"),
    # ── E: full characterization ───────────────────────────────────────
    Step("E1", "E. Full characterization (36-42 V packs)", "Orchestrated CC capacity test (NEB1002-H)",
         "6060B (manual CC <= the dashboard's FINAL PERMITTED, profile 1 A), OSBAMS, EDU34450A spot checks",
         "Run Capacity: OCV -> safety check -> READY -> confirm -> discharge to the profile cutoff -> load OFF verified -> recovery. "
         "Spot-check voltage with the EDU34450A at start, mid and end (record each).",
         "Automatic cutoff; load-off confirmed; Ah/Wh stored; spot-checks recorded; temperature below limit.", "D2"),
    Step("E2", "E. Full characterization (36-42 V packs)", "DCIR current-step test (NEB1002-H)",
         "6060B (manual), OSBAMS",
         "Run DCIR as a separate test on a rested pack; repeat 3 times with rest between.",
         "Three results recorded; repeatability reported (no tolerance claimed).", "E1"),
    Step("E3", "E. Full characterization (36-42 V packs)", "Thermal observation",
         "EDU34450A temperature function, TC74",
         "During E1/E2 compare pack-surface temperature (reference) with the TC74; record peak.",
         "Peak temperature recorded; stop-on-limit behaviour verified or marked untested.", "E1"),
    Step("E4", "E. Full characterization (36-42 V packs)", "Repeat on Shenzhen Elite (12.8 Ah) then NEE1006-M (15.3 Ah)",
         "as C1-E3 for each pack",
         "Same sequence including the relay-open OCV verification. Packs with BMS anomalies in the intake notes (blinking blue, cut wire) are inspected and judged safe BEFORE any connection.",
         "Per-pack records saved; no pack connected without an inspection note.", "E2"),
    Step("E5", "E. Full characterization (36-42 V packs)", "Passport and report reproducibility",
         "OSBAMS",
         "Generate the report and battery passport for each pack, regenerate them, and compare.",
         "Reports identical except timestamps; version block present.", "E1"),
    # ── F: remote control (blocked) ────────────────────────────────────
    Step("F1", "F. Remote control (blocked)", "Identify the SFSU GPIB path",
         "lab inventory",
         "USB<->GPIB adapter, LAN<->GPIB gateway or GPIB-equipped PC? Record models and the 6060B GPIB address "
         "(docs/rev2/GPIB_INTERFACE_CONFIRMATION.md).",
         "A concrete interface identified and recorded.", "A1"),
    Step("F2", "F. Remote control (blocked)", "Verify commands against the official manuals",
         "Electronic Load Family Programming Reference Manual; 6060B/6063B Operating Manual",
         "For each row of 6060B_DRIVER_EVIDENCE.md read the exact command, fill document + section/page, set VERIFIED.",
         "Operations are enabled only when every command they need is VERIFIED.", "F1"),
    Step("F3", "F. Remote control (blocked)", "First remote contact at low current",
         "6060B + GPIB path, EDU34450A, pack with relay supervised",
         "Construct Keysight6060B(interface_confirmed=True); identify, set_cc (<= 0.5 A), input_on/off, measure; compare with the EDU34450A.",
         "Readbacks agree with the reference; envelope guard refuses over-limit requests without writing.", "F2, D2"),
    Step("F4", "F. Remote control (blocked)", "Transient observation",
         "6060B remote, EDUX1052G",
         "Only if the transient commands are VERIFIED: configure a low-amplitude transient and observe the current step on the scope.",
         "Observed levels/frequency match the configuration.", "F3"),
]

STEP_BY_ID = {s.id: s for s in STEPS}


@dataclass
class StepRecord:
    step_id: str
    status: str = NOT_RUN
    operator: str = ""
    date: str = ""
    software_commit: str = ""
    tolerance_set_before_run: str = ""
    data_location: str = ""
    notes: str = ""


@dataclass
class ValidationLog:
    records: dict = field(default_factory=lambda: {s.id: StepRecord(s.id) for s in STEPS})

    def record(self, step_id: str, status: str, operator: str, **kw) -> StepRecord:
        if status not in STATUSES:
            raise ValueError(f"status must be one of {STATUSES}")
        step = STEP_BY_ID[step_id]
        if status == PASS:
            for dep in [d.strip() for d in step.blocked_by.split(",") if d.strip()]:
                if self.records[dep].status != PASS and not STEP_BY_ID[dep].optional:
                    raise ValueError(f"{step_id} requires {dep} to be PASS first")
            if not operator or not kw.get("data_location"):
                raise ValueError("PASS needs an operator and a data_location (recorded data)")
        r = self.records[step_id]
        r.status, r.operator = status, operator
        r.date = kw.pop("date", datetime.now().isoformat(timespec="seconds"))
        for k, v in kw.items():
            setattr(r, k, v)
        return r

    def next_step(self):
        for s in STEPS:
            if self.records[s.id].status != PASS and not s.optional:
                return s
        return None

    def save(self, path: str) -> None:
        with open(path, "w") as f:
            json.dump({k: asdict(v) for k, v in self.records.items()}, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "ValidationLog":
        log = cls()
        if os.path.exists(path):
            for k, v in json.load(open(path)).items():
                log.records[k] = StepRecord(**v)
        return log
