"""Review report, checklist, test-point map, assembly notes, functional test, README."""
import os, datetime
from reportlab.lib.units import mm
from . import pdfkit as K
from .pdfkit import P, table, H1, H2, BODY, SMALL, WARN
from . import parts

TODAY = datetime.date.today().isoformat()


def _pad(b, ref, num):
    for f in b.footprints:
        if f["ref"] == ref:
            for p in f["pads"]:
                if p["num"] == num:
                    gx, gy = b.g(p["x"], p["y"])
                    return f"({gx:.1f}, {gy:.1f}) mm"
    return "?"


# ─────────────────────────── review report ───────────────────────────
def review_md(ctx, issues):
    b, rv, gv, cv = ctx["board"], ctx["review"], ctx["gerber"], ctx["cpl"]
    L = []
    A = L.append
    A("# OSBAMS Rev.2 controller PCB — design review (pre-fabrication)\n")
    A(f"Generated {TODAY} by `tools/mfg` from `Hardware/Schematic/OSBAMS PCB.kicad_pcb` / `.kicad_sch` (KiCad format {b.version}).\n")
    A("> **Verdict: NOT READY FOR PRODUCTION.** Two critical findings (R1 diode polarity, R2 scope gap) and several open items "
      "are listed in §7. DRC and ERC were **not run** (no KiCad 10 available); every geometric number below is a script estimate, not a KiCad DRC result.\n")
    A("## 0. What the repository actually contains\n")
    A("| Item | Status |\n|---|---|")
    A("| KiCad schematic | `Hardware/Schematic/OSBAMS PCB.kicad_sch` — 16 symbols, label-based, single sheet, no title block |")
    A(f"| KiCad **PCB layout** | `Hardware/Schematic/OSBAMS PCB.kicad_pcb` — **a layout exists**: {len(b.footprints)} footprints (16 parts + 4 mounting holes), "
      f"{rv['board']['segments']} tracks (all F.Cu), {rv['board']['zones']} GND zone on B.Cu (filled), {rv['board']['vias']} vias, outline {b.width:g} × {b.height:g} mm |")
    A("| KiCad project | `Hardware/Schematic/OSBAMS PCB.kicad_pro` (a second, smaller `OSBAMS PCB.kicad_pro/.kicad_prl` sits at the repo root — stray duplicates) |")
    A("| Manufacturing outputs (Gerber/drill/CPL/PDF) | **none existed**; the candidates in this package were generated by script |")
    A("| DRC / ERC reports | none in the repo; **not run** |")
    A("| Older BOM spreadsheets | `Hardware/OSBAMS_BOM.xlsx`, `Documentation/OSBAMS_BOM.xlsx`, `Hardware/OSBAMS_Final_Design_Purchase_List.xlsx` describe a different/older system (Albright SW60, TBD parts); they do not match this PCB |\n")
    A("**The PCB is not the 'STM32L476RG + INA228 + ADC + USB/Pi' board described in the request.** It is a through-hole carrier: "
      "12 V input (J1) → reverse-polarity Schottky D3 → +12V (C1, TVS D1) → E-stop loop (J3) → contactor coil (J2) driven low-side by Q1 (R1/R2 gate network, D2 flyback); "
      "TC74 temperature sensor U1; 4-pin header J4 for an external INA228 breakout; 2×4 header J5 to an external NUCLEO-L476RG; 4-pin UART header J6. "
      "Only D1 is SMT.\n")
    A("Schematic vs PCB netlist comparison (script): **" + ("identical" if not rv["netlist_diffs"] else str(rv["netlist_diffs"])) + "** (refs, footprints and all 13 nets; "
      f"mismatches in refs/footprints: {rv['ref_footprint_mismatch'] or 'none'}).\n")

    A("## 1. Manufacturing review\n")
    A("### 1.1 Gerber / drill (script-generated candidates, re-read and checked)\n")
    A("| Check | Result |\n|---|---|")
    A(f"| Layers produced | {', '.join(gv['layers'])} + PTH and NPTH drill files |")
    A(f"| Empty layers (intentional: nothing on the bottom side except copper/mask) | {', '.join(gv['empty_layers']) or 'none'} |")
    A(f"| Board outline | 1 closed rectangle on Edge.Cuts, 4 line objects; measured from the Gerbers: **{gv['bbox_mm'][0]:g} × {gv['bbox_mm'][1]:g} mm** (design {b.width:g} × {b.height:g}) |")
    A(f"| Other objects on Edge.Cuts / mechanical layers | none (`gr_line/arc/circle/poly/text` = 0; User/Eco/Cmts/Dwgs layers empty) — no accidental mechanical layers |")
    A(f"| Copper objects | tracks on F.Cu only; GND zone on B.Cu only; no copper on any other layer, no keep-out/rule areas — no hidden copper |")
    A(f"| Drill holes | {gv['drill_pth_holes']} plated + {gv['drill_npth_holes']} non-plated; match the design: {gv['drill_pth_holes']==gv['expected_pth'] and gv['drill_npth_holes']==gv['expected_npth']}; hole positions re-read from the file match: {gv['pth_positions_match']} |")
    A(f"| Top-copper pad objects (flashes + rounded-rectangle regions) | {gv['copper_pad_objects_top']} vs {gv['expected_pads_top_cu']} pads expected: {'match' if gv['copper_pad_objects_top']==gv['expected_pads_top_cu'] else 'MISMATCH'} |")
    A("| Stack-up (from the PCB file) | 2 layers, 1.6 mm FR4, 35 µm copper (≈1 oz), mask 10 µm entry, **copper_finish = None (undefined)** |")
    A("| Silkscreen | footprint outlines, pin-1 markers, reference designators (stroke font), 'K' marks on D2/D3; **no clipping against pads/mask openings was applied** — KiCad's export must be used |")
    A("| Authority | **not** produced by KiCad: re-export with `export_with_kicad_cli.sh` before ordering |\n")
    A("### 1.2 Screening checks (script, approximate — confirm with KiCad DRC)\n")
    A("| Check | Result |\n|---|---|")
    A(f"| Unconnected nets | none found: every signal net is a single connected track group; GND connects through the B.Cu pour (see preview). `U1` pin 1 is an intentional NC |")
    A(f"| Dangling track ends | {rv['dangling_track_ends'] or 'none'} |")
    A(f"| Copper-to-edge < 0.5 mm | {rv['edge_clearance_lt_0.5'] or 'none'} |")
    A(f"| Clearance below the 0.2 mm net-class value | {rv['clearance_lt_0.2'] or 'none found'}; tightest values are exactly 0.2 mm: " + "; ".join(f"{d} ({t})" for d, t in rv["tightest_clearances"][:3]) + " |")
    A(f"| Courtyard overlaps | {rv['courtyard_overlaps'] or 'none'} |")
    A(f"| Reference text over pads (approx. text boxes) | {rv['silk_text_over_pads'] or 'none found'} |")
    A(f"| Annular ring < 0.15 mm | {', '.join(f'{r[0]} ({r[1]} mm)' for r in rv['annular_lt_0.15'])} |")
    A("| Drill sizes | smallest 0.8 mm (plated), largest 3.2 mm (NPTH); well inside normal fab limits |")
    A("| Component spacing | through-hole parts are widely spaced on an 80 × 80 mm board; no courtyard overlap |")
    A("| **KiCad DRC** | **NOT RUN** |")
    A("| **KiCad ERC** | **NOT RUN** |\n")

    A("## 2. Electrical review\n")
    A("### R1 — Diode polarity (CRITICAL)\n")
    A("Schematic: `OSBAMS:D_H` and `OSBAMS:D_TVS` draw the triangle base at pin 1 → **pin 1 = anode, pin 2 = cathode**. "
      "PCB footprints `D_DO-201AD_P15.24mm_Horizontal` and `D_SMB` are KiCad library parts whose **pad 1 = cathode** (square pad, 'K' on silk, band at pad 1; D1's silk bar at pad 1). Resulting connections:\n")
    A("| Diode | Role | Schematic intent | As built on the PCB |\n|---|---|---|---|")
    A("| D3 SB560 | series reverse-polarity | anode 12V_IN, cathode +12V | cathode (pad 1) on 12V_IN, anode on +12V → blocks the supply |")
    A("| D2 1N5408 | coil flyback | anode COIL_SW, cathode COIL_V | cathode (pad 1) on COIL_SW, anode on COIL_V → conducts +12V→Q1→GND when Q1 turns on, coil bypassed |")
    A("| D1 SMBJ15A | TVS on +12V | cathode +12V, anode GND | cathode (pad 1) on GND, anode on +12V → forward-conducts the rail to GND |")
    A("\nFix in KiCad (symbol pin numbering or footprint/net swap), update the PCB from the schematic, re-run DRC/ERC. **Not changed here.** ERC does not catch this because the symbol pins are 'passive'.\n")
    A("### R2 — Scope gap versus the requested controller functions (CRITICAL for the intended use)\n")
    A("| Requested review item | Finding |\n|---|---|")
    A("| STM32 decoupling | N/A — the STM32L476RG is on the external NUCLEO-L476RG. Only a 100 nF (C3) sits on +3V3 near J4/J6, C2 at the TC74. |")
    A("| INA228 layout / Kelvin sensing | N/A on this PCB — INA228 is an external breakout; its shunt/VBUS wiring (Kelvin routing) is off-board. J4 carries 3V3/GND/SCL/SDA only. |")
    A("| Analog/digital grounding | one B.Cu solid GND pour; 12 V coil return current (Q1 source → pour → J1) shares it with logic ground; no split. Acceptable for this simple board; no analog front end exists. |")
    A("| ADC routing | **none** — no independent ADC voltage divider on the PCB (firmware/docs expect one). |")
    A("| Power rails | +12V (after D3), +3V3 (from Nucleo via J5.1). **No 5 V rail, no regulator.** |")
    A("| Protection circuits | D3 reverse-polarity, D1 TVS (15 V standoff), D2 flyback, C1 bulk — all subject to R1. No input fuse on the PCB (external F2 control fuse assumed); no ESD protection on UART/I2C headers. |")
    A("| Relay driver | Q1 IRLZ44N low-side, R1 220 Ω gate, R2 10 kΩ pull-down, D2 flyback. Gate drive from a 3.3 V GPIO (J5.5); IRLZ44N is logic-level but Rds(on) is specified at 4–5 V — fine for a small coil, not verified here. Default state: gate pulled low = coil off (good). |")
    A("| E-stop monitoring | **loop only** (J3 in series with the coil supply — hardware interruption works). **No E-stop status line to the MCU**; firmware expects PA0. |")
    A("| Relay feedback / ARM input / USB / programming header / test points | **absent** |\n")
    A("### R3 — Other electrical observations\n")
    A("- **Track widths:** every track is 0.3 mm including +12V/COIL_V/COIL_SW; the 1.2 mm 'Powerpath' net class was not applied (patterns lack the leading '/'). Coil current is not specified in the repo.\n"
      "- **C1** 25 V electrolytic vs the TVS clamp (~24 V at SMBJ15A peak) — thin margin; consider 35 V.\n"
      "- **I2C:** TC74A5 at 0x4D, INA228 at 0x40 — no address conflict; pull-ups are not on this PCB (they are on the Nucleo/breakout side — confirm).\n"
      "- **U1 annular ring** 0.087 mm on the narrow axis — below the typical 0.15 mm fab minimum.\n"
      "- **J5** described as keyed; footprint is a plain header.\n")

    A("## 3. Production review\n")
    A("| Check | Result |\n|---|---|")
    A("| Component availability | **not checked** (no network access to PCBWay/LCSC/distributors) |")
    A("| Obsolete parts | **not checked**; IRLZ44N (now Infineon), 1N5408, SB560, TC74, ECA-series electrolytics are long-lived families but status must be confirmed |")
    A("| Substitutions | **none made.** Safety/measurement parts (U1, Q1, D1–D3, R2) are flagged 'do not substitute without approval' |")
    A("| Package correctness | Q1 pinout G-D-S matches TO-220 footprint; U1 TC74 (TO-220-5: NC, SDA, GND, SCLK, VDD) matches; C1 + on pad 1 correct; D1–D3 polarity: see R1; D1 package DO-214AA/SMB correct for SMBJ15A |")
    A("| BOM completeness | 14 BOM lines; **MPN missing for R1, R2, C2, C3, J1–J6**; manufacturer missing for D1, D2 |")
    A("| Assembly type | 1 SMT (D1) + 15 THT parts |\n")

    A("## 4. Test points\nNone on the PCB. See `OSBAMS_Rev2_Test_Point_Map.pdf` for existing probe pads and a proposed (not implemented) list.\n")
    A("## 5. Preview images\n`preview_top_from_gerber.png`, `preview_bottom_from_gerber.png` were rendered from the generated Gerber files.\n")
    A("## 6. Candidate-file caveat\nAll fabrication files in this package were written by `tools/mfg` (gerbonara) because KiCad 10 is unavailable. They are consistent with the design file (hole positions, outline, pad counts re-read from the written files) but have not been compared with a KiCad plot or PCBWay DFM.\n")
    A("## 7. Unresolved issues preventing production\n")
    A("| ID | Severity | Issue | Detail | Required action |\n|---|---|---|---|---|")
    for i in issues:
        A(f"| {i[0]} | {i[1]} | {i[2]} | {i[3]} | {i[4]} |")
    A("\n**The board is not production-ready.** Do not upload these files to PCBWay until U1–U4 are closed.\n")
    return "\n".join(L)


# ─────────────────────────── checklist ───────────────────────────
def checklist_md(ctx, issues):
    b, rv, gv, cv = ctx["board"], ctx["review"], ctx["gerber"], ctx["cpl"]
    ok = lambda c: "✅ PASS" if c else "❌ FAIL"
    missing_mpn = [r for p in parts.PARTS if p["mpn"] == parts.NOT_SPEC for r in p["refs"]]
    L = ["# OSBAMS Rev.2 controller PCB — PCBWay production readiness checklist\n",
         f"Generated {TODAY}. **Overall: NOT PRODUCTION-READY** — see the failed items and the issue list at the end.\n",
         "| # | Item | Status | Evidence / note |", "|---|---|---|---|"]
    rows = [
        ("A KiCad PCB layout exists", True, f"Hardware/Schematic/OSBAMS PCB.kicad_pcb: {len(b.footprints)} footprints, {len(b.segments)} tracks, 1 GND zone, {b.width:g}×{b.height:g} mm outline"),
        ("Gerbers generated", True, "script-generated CANDIDATES (copper, mask, silk, paste, edge, drill) — **not** exported by KiCad"),
        ("Gerbers exported by KiCad / checked by KiCad", False, "KiCad 10 unavailable; run tools/mfg/export_with_kicad_cli.sh"),
        ("Layer set complete, no stray mechanical layers", True, f"{len(gv['layers'])} graphic layers + 2 drill files; nothing on mechanical/user layers"),
        ("Board dimensions correct", abs(gv['bbox_mm'][0]-b.width) < 0.01 and abs(gv['bbox_mm'][1]-b.height) < 0.01, f"{gv['bbox_mm'][0]:g} × {gv['bbox_mm'][1]:g} mm read back from the Gerbers"),
        ("Drill files complete", gv["pth_positions_match"] and gv["drill_pth_holes"] == gv["expected_pth"], f"{gv['drill_pth_holes']} PTH + {gv['drill_npth_holes']} NPTH"),
        ("BOM file complete (all required columns filled, specific descriptions; unknown values flagged)", True, "14 lines, specific descriptions/packages; unknown fields marked NOT SPECIFIED rather than invented"),
        ("All parts have a manufacturer part number", not missing_mpn, "missing MPN: " + ", ".join(missing_mpn)),
        ("No TBD / unspecified components", not missing_mpn, "same rows; also D1/D2 manufacturer unnamed"),
        ("CPL complete for every SMT part", cv["all_placed"] and not cv["duplicates"] and not cv["missing_rotation"], f"SMT parts: {cv['smd_parts']}; rows: {cv['cpl_rows']}; duplicates: {cv['duplicates']}; missing rotation: {cv['missing_rotation'] or 'none'}"),
        ("CPL polarity of D1 verified", False, "D1 polarity is an open issue (U1)"),
        ("No missing footprints", not rv["ref_footprint_mismatch"], f"schematic vs PCB refs/footprints: {rv['ref_footprint_mismatch'] or 'consistent'}"),
        ("Schematic and PCB netlists agree", not rv["netlist_diffs"], "script comparison: 0 differences"),
        ("Diode polarity consistent (schematic vs footprint)", False, "D1, D2, D3 mismatch — CRITICAL"),
        ("DRC passed", False, "NOT RUN (script screening found no clearance < 0.2 mm, but this is not DRC)"),
        ("ERC passed", False, "NOT RUN"),
        ("Assembly drawing, schematic PDF, test-point map, assembly notes, functional test produced", True, "script-generated; see Documentation/Assembly/Testing"),
        ("Assembly notes complete", True, "OSBAMS_Rev2_Assembly_Notes.pdf (polarity items marked HOLD)"),
        ("Controller functions present on the PCB (STM32, INA228, ADC, E-stop sense, USB/Pi, 5 V)", False, "external modules / absent — scope gap (U2)"),
        ("Test points present", False, "none on the PCB"),
        ("Component availability confirmed", False, "not checked (no network)"),
        ("Surface finish / mask colour / order options defined", False, "stackup copper_finish = None"),
    ]
    for i, (name, status, note) in enumerate(rows, 1):
        L.append(f"| {i} | {name} | {ok(status)} | {note} |")
    L += ["", "## Unresolved issues preventing production\n", "| ID | Severity | Issue | Required action |", "|---|---|---|---|"]
    for it in issues:
        L.append(f"| {it[0]} | {it[1]} | {it[2]} | {it[4]} |")
    L += ["", "**Do not claim this board production-ready until every FAIL above is closed and the files are re-exported from KiCad.**", ""]
    return "\n".join(L)


# ─────────────────────────── PDFs ───────────────────────────
def test_point_pdf(ctx, path):
    b = ctx["board"]
    st = [P("OSBAMS Rev.2 controller PCB — test point map", H1),
          P("<b>The PCB has NO dedicated test points.</b> Part A lists the existing pads that can be probed today; Part B is the requested list adapted to this board "
            "(items that need a layout change are marked NOT ON PCB — the design was not modified). Coordinates: mm from the lower-left board corner, Y up.", WARN),
          P("Part A — existing probe points", H2)]
    A = [["Signal", "Best probe pad", "Alternates", "Purpose"],
         ["+12V (after D3)", f"C1 pad 1 {_pad(b,'C1','1')}", f"D3 pad 2 {_pad(b,'D3','2')}, J3 pad 1 {_pad(b,'J3','1')}", "supply verification (needs D3 correctly oriented)"],
         ["12V_IN (before D3)", f"J1 pad 1 {_pad(b,'J1','1')}", f"D3 pad 1 {_pad(b,'D3','1')}", "input present / reverse-polarity check"],
         ["GND", f"J1 pad 2 {_pad(b,'J1','2')}", f"C1 pad 2 {_pad(b,'C1','2')}, J5 pad 2, any GND pad (B.Cu pour)", "reference"],
         ["+3V3 (from Nucleo)", f"J5 pad 1 {_pad(b,'J5','1')}", f"J4 pad 1 {_pad(b,'J4','1')}, U1 pad 5 {_pad(b,'U1','5')}, J6 pad 1", "logic rail"],
         ["SDA (I2C)", f"J4 pad 4 {_pad(b,'J4','4')}", f"J5 pad 3 {_pad(b,'J5','3')}, U1 pad 2 {_pad(b,'U1','2')}", "TC74 / INA228 bus"],
         ["SCL (I2C)", f"J4 pad 3 {_pad(b,'J4','3')}", f"J5 pad 4 {_pad(b,'J5','4')}, U1 pad 4 {_pad(b,'U1','4')}", "TC74 / INA228 bus"],
         ["UART_TX", f"J6 pad 3 {_pad(b,'J6','3')}", f"J5 pad 6 {_pad(b,'J5','6')}", "debug / Pi link (3.3 V)"],
         ["UART_RX", f"J6 pad 4 {_pad(b,'J6','4')}", f"J5 pad 7 {_pad(b,'J5','7')}", "debug / Pi link (3.3 V)"],
         ["GPIO_GATE (MCU output)", f"J5 pad 5 {_pad(b,'J5','5')}", f"R1 pad 1 {_pad(b,'R1','1')}", "relay-driver command"],
         ["GATE (MOSFET gate)", f"R1 pad 2 {_pad(b,'R1','2')}", f"Q1 pad 1 {_pad(b,'Q1','1')}, R2 pad 1", "gate drive after R1"],
         ["COIL_SW (MOSFET drain)", f"Q1 pad 2 {_pad(b,'Q1','2')}", f"J2 pad 2 {_pad(b,'J2','2')}, D2 pad 1", "coil switch node"],
         ["COIL_V (coil supply)", f"J2 pad 1 {_pad(b,'J2','1')}", f"J3 pad 2 {_pad(b,'J3','2')}, D2 pad 2", "E-stop-gated coil supply"]]
    st.append(table(A, [32 * mm, 48 * mm, 62 * mm, 38 * mm], font=7))
    st.append(P("Part B — requested test points adapted to this board", H2))
    B = [["TP", "Signal", "Purpose", "Status on this PCB"],
         ["TP1", "12V", "supply verification", "no TP — probe C1.1 / D3.2 (Part A)"],
         ["TP2", "5V", "logic rail", "NOT ON PCB — there is no 5 V rail"],
         ["TP3", "3.3V", "MCU rail", "no TP — probe J5.1 (3.3 V comes from the Nucleo)"],
         ["TP4", "GND", "reference", "no TP — any GND pad / pour"],
         ["TP5", "INA228 SDA", "communication", "no TP — J4 pad 4 (module header)"],
         ["TP6", "INA228 SCL", "communication", "no TP — J4 pad 3"],
         ["TP7", "ADC voltage", "calibration", "NOT ON PCB — there is no ADC divider"],
         ["TP8", "UART TX", "debug", "no TP — J6 pad 3"],
         ["TP9", "UART RX", "debug", "no TP — J6 pad 4"],
         ["TP10", "E-stop", "safety state", "NOT ON PCB — J3 is a series loop; there is no E-stop sense signal"],
         ["(new)", "COIL_SW / GATE", "relay-driver check", "no TP — Q1 pads (Part A)"]]
    shade = [(i, K.BAD) for i, r in enumerate(B) if r[3].startswith("NOT ON PCB")]
    st.append(table(B, [14 * mm, 28 * mm, 32 * mm, 106 * mm], font=7.2, shade=shade))
    st.append(P("Recommendation (design change, not done): add labelled 1 mm test pads for +12V, +3V3, GND, SDA, SCL, GATE, COIL_SW before a production order.", BODY))
    K.build(path, st, "Test point map")


def assembly_notes_pdf(ctx, path):
    st = [P("OSBAMS Rev.2 controller PCB — assembly notes", H1),
          P("<b>Purpose.</b> OSBAMS Rev.2 Controller PCB is a battery measurement and safety-control board. The PCB does not carry the main battery discharge current. "
            "High-current battery connections are external."),
          P("STATUS: NOT RELEASED. Do not start assembly until the HOLD items below are cleared in writing by the design owner.", WARN),
          P("Important assembly rules", H2)]
    for t in ["<b>Do not substitute the STM32</b> (NUCLEO-L476RG / STM32L476RG) without approval — it is a plug-in module, not assembled by the fab.",
              "<b>Do not substitute the INA228</b> (Adafruit 5832 breakout) without approval — plug-in module, not assembled by the fab.",
              "<b>Maintain the measurement components:</b> U1 TC74A5-3.3VAT (Microchip) must not be replaced by another sensor or address variant.",
              "<b>Safety parts — no substitution without approval:</b> Q1 IRLZ44NPBF, R2 gate pull-down, D1/D2/D3 (once polarity is resolved).",
              "<b>Verify connector orientation:</b> J1–J3 (terminal blocks, wire entry toward the board edge as designed), J4/J5/J6 pin 1 at the square pad. J5 is not physically keyed.",
              "<b>Verify the programming header:</b> there is NO programming header on this PCB; programming is through the ST-LINK on the Nucleo module. Do not fit anything in J5/J6 other than the intended modules.",
              "<b>Verify polarity-sensitive parts:</b> C1 (+ on pad 1), D1/D2/D3 (cathode band; <b>HOLD — schematic and footprint disagree</b>), Q1 (G-D-S), U1 (pin 1 NC, square pad).",
              "<b>Do not fit</b> the battery fuse, XT60 power connector, disconnect, relay contacts, shunt wiring or the 6060B connection — external power hardware.",
              "No battery or high-energy source is to be connected during factory work."]:
        st.append(P("• " + t))
    st.append(P("Part-by-part notes", H2))
    rows = [["Ref", "Part", "Mount", "Orientation / note"]]
    for p in parts.PARTS:
        rows.append([", ".join(p["refs"]), f"{p['value']} / {p['mpn']}", "SMT" if p["refs"] == ["D1"] else "THT", p["notes"]])
    st.append(table(rows, [16 * mm, 44 * mm, 12 * mm, 108 * mm], font=6.8))
    st.append(P("Process notes", H2))
    for t in ["Order mix: 1 SMT part (D1) on the top side; all other parts through-hole, top side only. No bottom-side components.",
              "TO-220 parts (Q1, U1) mount vertically with the leads through the board; no heat sink or insulation hardware is specified.",
              "Terminal blocks carry the 12 V coil current only; wire gauge by the user.",
              "Cleaning: no-clean flux acceptable; avoid flux residue on headers J4/J5/J6.",
              "Mounting holes MH1–MH4 are 3.2 mm non-plated; keep mask/paste out of them.",
              "Silkscreen has designators only — no polarity legend on J1–J3; refer to the Assembly Drawing pin/polarity map."]:
        st.append(P("• " + t))
    K.build(path, st, "Assembly notes")


def functional_test_pdf(ctx, path):
    st = [P("OSBAMS Rev.2 controller PCB — factory functional test (optional)", H1),
          P("<b>Do NOT connect a battery during factory PCB testing.</b> Use only the bench supplies named below. "
            "This board has no MCU, no USB and no ADC of its own, so the test list is adapted: steps that need the plug-in Nucleo/INA228 modules are marked as customer-side. "
            "Expected values are design estimates, not measured data.", WARN),
          P("Preconditions: D1/D2/D3 polarity issue (review item R1) resolved and the board rebuilt; external modules NOT fitted unless stated.", BODY)]
    rows = [["#", "Step", "Method", "Expected / pass criterion"],
            ["1", "Visual inspection", "Compare with the Assembly Drawing: C1 +, D1–D3 band, Q1/U1 orientation, headers, no solder bridges, no missing parts.", "All parts present and oriented per the corrected drawing."],
            ["2", "Short-circuit check (power off)", "Ohmmeter: +12V–GND, 12V_IN–GND, +3V3–GND, COIL_V–COIL_SW, GATE–GND.", "No dead shorts (all > 100 ohm; GATE–GND ≈ 10 kΩ via R2)."],
            ["3", "Apply logic power", "Bench 3.3 V, current limit 50 mA, to J5 pad 1 (+3V3) and pad 2 (GND). No Nucleo fitted.", "Supply draws < 10 mA."],
            ["4", "Verify 3.3 V rail", "Voltmeter on J4.1, J6.1, U1.5, C3.", "3.3 V ± 5 % at each point."],
            ["5", "Program STM32", "N/A at the fab — the STM32 is on the Nucleo module (ST-LINK on that module).", "Customer-side."],
            ["6", "Confirm USB/UART", "No USB on this board. Continuity J5.6–J6.3 (UART_TX) and J5.7–J6.4 (UART_RX).", "Continuity < 1 ohm; no crosstalk between the two."],
            ["7", "Confirm INA228 communication", "Customer-side with the INA228 breakout fitted. At the fab: continuity J4.3–J5.4 (SCL), J4.4–J5.3 (SDA).", "Continuity OK; I2C ACK at 0x40 customer-side."],
            ["8", "Confirm ADC channel", "N/A — this PCB has no ADC channel.", "Not applicable."],
            ["9", "Confirm temperature interface", "3.3 V on, read TC74 over I2C with a customer adapter at address 0x4D (or check SDA/SCL continuity J5↔U1).", "ACK at 0x4D customer-side; continuity J5.3–U1.2, J5.4–U1.4."],
            ["10", "Confirm relay-driver output", "Bench 12 V (current limit 0.5 A) on J1 (pad 1 = +, pad 2 = GND). 24 ohm / 6 W resistor on J2 as a coil stand-in, J3 shorted with a wire. Drive J5.5 to 3.3 V through 1 kΩ, then release.", "+12V ≈ 11.4–11.8 V (Schottky drop); COIL_SW ≈ 0.1 V and the load draws ≈ 0.5 A with the gate high; COIL_SW ≈ +12 V and no current with the gate low. Open J3: no current in either state."],
            ["11", "Reverse-polarity check", "Bench 12 V with reversed polarity, current limit 0.2 A.", "No current (D3 blocks)."]]
    st.append(table(rows, [8 * mm, 36 * mm, 76 * mm, 60 * mm], font=7.4))
    st.append(P("Record: serial/lot, date, operator, measured values and pass/fail for each step. Any failed step = hold the board.", BODY))
    K.build(path, st, "Functional test")


# ─────────────────────────── README ───────────────────────────
def readme_md(ctx, issues):
    L = ["# PCBWay_OSBAMS_Rev2_PCBA — package index\n",
         "**STATUS: NOT PRODUCTION-READY. Do not upload yet.** All fabrication files are script-generated *candidates* (KiCad 10 was unavailable). See `Documentation/OSBAMS_Rev2_PCBWAY_CHECKLIST.md`.\n",
         "| Folder | Contents |", "|---|---|",
         "| `Gerber/` | copper (F/B), mask, silkscreen, paste, edge cuts + `OSBAMS_Rev2_Gerber.zip` (Gerber + drill + candidate notice) |",
         "| `Drill/` | Excellon PTH / NPTH + drill report |",
         "| `BOM/` | `OSBAMS_Rev2_BOM.xlsx` (BOM, External_not_assembled, Legend) |",
         "| `PickAndPlace/` | `OSBAMS_Rev2_CPL.csv` (SMT only: D1) + all-parts reference CSV |",
         "| `Assembly/` | `OSBAMS_Rev2_Assembly_Drawing.pdf`, `OSBAMS_Rev2_Assembly_Notes.pdf` |",
         "| `Documentation/` | schematic PDF, PCB review, test-point map, checklist, previews, `export_with_kicad_cli.sh` |",
         "| `Testing/` | `OSBAMS_Rev2_Functional_Test.pdf` |\n",
         "Regenerate everything: `python3 -m tools.mfg.build_package` (repo root).\n",
         "## What the board is\nA through-hole carrier (80 × 80 mm, 2 layers): 12 V in, D3/D1/C1 protection, E-stop loop J3, MOSFET relay-coil driver Q1/D2/J2, TC74 sensor U1, headers for an external INA228 breakout (J4), NUCLEO-L476RG (J5) and UART (J6). "
         "The STM32/INA228 are modules, not on the PCB; battery fuse, XT60 power connector, disconnect, relay contacts and shunt wiring are external.\n",
         "## Unresolved issues\n"]
    for it in issues:
        L.append(f"- **{it[0]} ({it[1]}): {it[2]}** — {it[4]}")
    return "\n".join(L) + "\n"


def write_all(ctx, SUB, OUT, issues):
    open(os.path.join(SUB["Documentation"], "OSBAMS_Rev2_PCB_REVIEW.md"), "w").write(review_md(ctx, issues))
    open(os.path.join(SUB["Documentation"], "OSBAMS_Rev2_PCBWAY_CHECKLIST.md"), "w").write(checklist_md(ctx, issues))
    test_point_pdf(ctx, os.path.join(SUB["Documentation"], "OSBAMS_Rev2_Test_Point_Map.pdf"))
    assembly_notes_pdf(ctx, os.path.join(SUB["Assembly"], "OSBAMS_Rev2_Assembly_Notes.pdf"))
    functional_test_pdf(ctx, os.path.join(SUB["Testing"], "OSBAMS_Rev2_Functional_Test.pdf"))
    open(os.path.join(OUT, "README.md"), "w").write(readme_md(ctx, issues))
