"""Text content and PDF/MD writers for the PCBWay package."""
import os, datetime
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
from reportlab.lib.units import mm
from reportlab.platypus import Spacer, PageBreak
from . import pdfkit as K
from .pdfkit import P, table, H1, H2, BODY, SMALL, WARN

TODAY = datetime.date.today().isoformat()

GERBER_ZIP_NOTICE = """CANDIDATE FILES - NOT A KICAD EXPORT
These Gerber/Excellon files were generated by tools/mfg (Python + gerbonara) directly from
'OSBAMS PCB.kicad_pcb' because KiCad 10 / kicad-cli was not available in the build environment.
Geometry was verified by re-reading the files and rendering them, but they have NOT been checked
against KiCad's own plot, DRC or a PCBWay DFM review. Do not order from this zip: re-export with
tools/mfg/export_with_kicad_cli.sh (KiCad 10), diff, then upload the KiCad files.
Known open issues that block production are listed in OSBAMS_Rev2_PCBWAY_CHECKLIST.md.
"""

BOM_LEGEND = [
    "OSBAMS Rev.2 controller PCB - BOM generated from 'OSBAMS PCB.kicad_sch' / .kicad_pcb by tools/mfg",
    "Rows marked NOT SPECIFIED (red) have no manufacturer / MPN in the design files. Nothing was substituted or invented;",
    "the customer must choose and approve those parts. 'Notes' says what each part needs.",
    "PCBWay/JLC availability was NOT checked (no network access from the build environment).",
    "The STM32L476RG (NUCLEO-L476RG) and INA228 (Adafruit 5832 breakout) are external modules and are not on this PCB - see sheet External_not_assembled.",
    "Battery fuse, disconnect, shunt, XT60 power connector and relay contacts are external power hardware and are not part of this assembly.",
]

CPL_README = """OSBAMS_Rev2_CPL.csv lists the SMT components only (PCBWay assembles SMT from the CPL): D1 (SMBJ15A, SMB).
All other parts are through-hole; OSBAMS_Rev2_CPL_ALL_PARTS_reference_THT_included.csv lists every placed footprint for
reference (THT assembly instructions are in the assembly notes).
Coordinates: millimetres, origin = lower-left corner of the board outline, Y up (same origin as the Gerber and drill files).
Rotation: KiCad footprint orientation (degrees, counter-clockwise). D1 = 0 deg: pad 1 (cathode per KiCad's D_SMB footprint) on the
LEFT. D1's electrical polarity is an OPEN ISSUE (schematic puts the cathode on +12V; the PCB puts pad 1 = cathode on GND) - see the review.
Have PCBWay confirm D1 orientation against their library before assembly.
"""

DRAWING_CALLOUTS = [
    "STM32L476RG: NOT on this PCB - it is on the NUCLEO-L476RG module that plugs into J5.",
    "INA228: NOT on this PCB - external Adafruit breakout plugs into J4 (3V3/GND/SCL/SDA).",
    "Programming header: NONE on this PCB (ST-LINK is on the Nucleo module).",
    "Test points: NONE on this PCB (see Test Point Map).",
    "Analog measurement section: none beyond the I2C sensors (no ADC divider on this PCB).",
    "! D1, D2, D3: 'pad 1' is the CATHODE per the KiCad footprints but the schematic",
    "! symbol has pin 1 = ANODE -> polarity mismatch. Do NOT assemble until resolved.",
    "Square pad / red '1' = pin 1 of connectors. C1 electrolytic: + = pad 1.",
    "Board carries only 12 V coil current, NOT the battery discharge current.",
]
DRAWING_BOTTOM = [
    "Bottom side: no components.",
    "B.Cu is a solid GND pour (thermal-relief connections",
    "to GND pads); all signal tracks are on F.Cu.",
    "No bottom silkscreen, no bottom paste.",
]


def _pin_table(b):
    rows = [["Ref", "Pad", "Net", "Notes"]]
    notes = {("J1", "1"): "12V_IN (+12 V input, before D3)", ("J1", "2"): "GND", ("J2", "1"): "COIL_V (coil +, via E-stop loop)",
             ("J2", "2"): "COIL_SW (coil -, MOSFET drain)", ("J3", "1"): "+12V (E-stop loop in)", ("J3", "2"): "COIL_V (E-stop loop out)",
             ("J4", "1"): "+3V3", ("J4", "2"): "GND", ("J4", "3"): "SCL", ("J4", "4"): "SDA",
             ("J6", "1"): "+3V3", ("J6", "2"): "GND", ("J6", "3"): "UART_TX", ("J6", "4"): "UART_RX",
             ("Q1", "1"): "Gate", ("Q1", "2"): "Drain", ("Q1", "3"): "Source", ("U1", "1"): "NC", ("U1", "2"): "SDA",
             ("U1", "3"): "GND", ("U1", "4"): "SCLK", ("U1", "5"): "VDD (3.3 V)",
             ("C1", "1"): "+ (positive)", ("C1", "2"): "- (negative)",
             ("D1", "1"): "pad 1 = CATHODE (footprint) - on GND  [MISMATCH]", ("D1", "2"): "pad 2 = anode (footprint) - on +12V  [MISMATCH]",
             ("D2", "1"): "pad 1 = CATHODE (footprint) - on COIL_SW  [MISMATCH]", ("D2", "2"): "pad 2 = anode (footprint) - on COIL_V  [MISMATCH]",
             ("D3", "1"): "pad 1 = CATHODE (footprint) - on 12V_IN  [MISMATCH]", ("D3", "2"): "pad 2 = anode (footprint) - on +12V  [MISMATCH]"}
    for f in sorted(b.footprints, key=lambda f: f["ref"]):
        if f["ref"].startswith("MH"):
            continue
        for p in sorted([q for q in f["pads"] if q["num"].isdigit()], key=lambda p: int(p["num"])):
            rows.append([f["ref"], p["num"], (p["net"] or "-").lstrip("/"), notes.get((f["ref"], p["num"]), p["func"])])
    return rows


def drawing_notes_pdf(b, path):
    st = [P("OSBAMS Rev.2 controller PCB - polarity, orientation and special assembly notes", H1),
          P("Generated from the KiCad design files. Pin-1 and polarity data below are read from the PCB netlist/footprints.", SMALL),
          P("Special assembly notes", H2)]
    for t in [
        "<b>Scope:</b> this PCB does not carry the battery discharge current. It is a 12 V coil-driver / sensor-interface carrier board. "
        "Battery fuse, disconnect, relay contacts, shunt wiring, XT60 power connector and the 6060B connection are external.",
        "<b>Modules are not assembled by the fab:</b> the NUCLEO-L476RG (STM32L476RG) and the INA228 breakout are plugged in by the customer.",
        "<b>SMT:</b> only D1 (SMBJ15A, DO-214AA/SMB, top side). Everything else is through-hole (TO-220 x2, axial parts, radial parts, terminal blocks, pin headers).",
        "<b style='color:#a00000'>Diodes D1, D2, D3 - HOLD:</b> the KiCad footprints put the cathode on pad 1; the schematic symbol puts the anode on pin 1. "
        "As drawn, the PCB connects each diode's cathode to the wrong net. Resolve in KiCad, regenerate, then assemble.",
        "<b>C1</b> electrolytic: + lead in pad 1 (square/rounded pad, silkscreen '+').",
        "<b>Q1 (TO-220-3):</b> pins G-D-S left to right as marked; <b>U1 (TC74, TO-220-5):</b> pin 1 = NC at the square pad.",
        "<b>J5 (2x4 header):</b> schematic calls it keyed, the footprint is not; mark orientation with pin-1 square pad. <b>J6</b> uses a polarised fan-header footprint.",
        "<b>Do not substitute</b> U1, Q1, D1, D2, D3, R2 (gate pull-down) or the external STM32/INA228 modules without written approval.",
        "Mounting holes MH1-MH4: 3.2 mm NPTH for M3 hardware (not supplied).",
    ]:
        st.append(P(t))
    st += [P("Pin / polarity map", H2), table(_pin_table(b), [18 * mm, 12 * mm, 32 * mm, 108 * mm], font=7)]
    K.build(path, st, "Assembly drawing - notes")


def power_tree_figure():
    fig = plt.figure(figsize=(11.69, 8.27))
    ax = fig.add_axes([0.02, 0.05, 0.96, 0.82]); ax.axis("off"); ax.set_xlim(0, 100); ax.set_ylim(0, 60)
    fig.text(0.03, 0.95, "OSBAMS Rev.2 controller PCB - power tree", fontsize=13, fontweight="bold")
    fig.text(0.03, 0.925, "Derived from the netlist. There is NO 5 V rail and NO regulator on this PCB; 3.3 V comes from the Nucleo module.", fontsize=7, color="#a00")
    def box(x, y, w, h, t, fc="#e6eef8"):
        ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.3", fc=fc, ec="#345"))
        ax.text(x + w / 2, y + h / 2, t, ha="center", va="center", fontsize=7)
    def arr(x0, y0, x1, y1, t=""):
        ax.annotate("", (x1, y1), (x0, y0), arrowprops=dict(arrowstyle="->", color="#333"))
        if t: ax.text((x0 + x1) / 2, (y0 + y1) / 2 + 0.8, t, fontsize=6, ha="center", color="#0000aa")
    box(2, 44, 16, 8, "External 12 V supply\n(not on this PCB;\nconnects at J1)", "#f4e6d0")
    box(24, 44, 14, 8, "J1 PWR_IN_12V\n(12V_IN / GND)"); arr(18, 48, 24, 48)
    box(44, 44, 14, 8, "D3 SB560\nreverse-polarity\nSchottky"); arr(38, 48, 44, 48, "12V_IN")
    box(64, 44, 14, 8, "+12V rail", "#d9f0d9"); arr(58, 48, 64, 48)
    box(84, 50, 14, 6, "D1 SMBJ15A TVS\n(+12V to GND)", "#f0d9f0"); arr(78, 49, 84, 52)
    box(84, 41, 14, 6, "C1 10 uF 25 V\n(+12V to GND)", "#f0d9f0"); arr(78, 46, 84, 44)
    box(64, 30, 14, 8, "J3 E-STOP LOOP\n(hardware: opens\ncoil supply)"); arr(71, 44, 71, 38, "+12V")
    box(64, 16, 14, 8, "COIL_V"); arr(71, 30, 71, 24, "")
    box(44, 16, 14, 8, "J2 CONTACTOR_COIL\n(external coil)"); arr(64, 20, 58, 20, "COIL_V")
    box(44, 4, 14, 8, "COIL_SW\nQ1 IRLZ44N drain"); arr(51, 16, 51, 12)
    box(84, 22, 14, 8, "D2 1N5408 flyback\nacross the coil\n(COIL_V <-> COIL_SW)", "#f0d9f0")
    box(64, 4, 14, 8, "GND (B.Cu pour)", "#d9d9d9"); arr(58, 8, 64, 8, "Q1 source")
    box(2, 28, 16, 8, "NUCLEO-L476RG\n(external module)\nsupplies +3V3", "#f4e6d0")
    box(24, 28, 14, 8, "J5 NUCLEO_INTERFACE"); arr(18, 32, 24, 32)
    box(2, 4, 16, 8, "+3V3 loads:\nJ4 INA228 header, U1 TC74,\nJ6 UART header,\nC2/C3 bypass", "#d9f0d9"); arr(30, 28, 12, 12, "+3V3")
    box(24, 4, 14, 8, "GATE drive:\nJ5.5 GPIO_GATE -> R1 220R\n-> Q1 gate, R2 10k pull-down"); arr(31, 28, 31, 12)
    ax.text(2, 58, "No ADC divider, no E-stop sense line, no relay-feedback input, no 5 V rail on this PCB.", fontsize=7.5, color="#a00000")
    return fig


def schematic_cover_pdf(s, review, path):
    st = [P("OSBAMS Rev.2 controller PCB - schematic package", H1),
          P(f"Source: Hardware/Schematic/OSBAMS PCB.kicad_sch (KiCad format {s.version}) | generated {TODAY} by tools/mfg", SMALL),
          P("STATUS: NOT RELEASED FOR PRODUCTION. These pages are drawn by a script from the KiCad file (KiCad was not available); they are not a KiCad plot and ERC has not been run. "
            "Export the authoritative PDF with tools/mfg/export_with_kicad_cli.sh.", WARN),
          P("Contents", H2),
          P("1. Complete schematic (single sheet). 2-5. The four schematic sections. 6. Power tree. 7. Section coverage vs the requested list. 8. Netlist and component list."),
          P("What this board is", H2),
          P("A through-hole carrier board: 12 V input with reverse-polarity diode and TVS, a low-side MOSFET driver for the contactor coil with E-stop loop and flyback diode, "
            "a TC74 temperature sensor, a header for an external INA228 breakout, a 2x4 header to an external NUCLEO-L476RG and a 4-pin UART header. "
            "Net connectivity of the schematic and PCB was compared by script: identical (0 differences)."),
          P("Schematic observations", H2)]
    for t in ["Diode symbol (OSBAMS:D_H, OSBAMS:D_TVS): pin 1 is the ANODE (triangle base) and pin 2 the CATHODE. KiCad's D_DO-201AD and D_SMB footprints use pad 1 = CATHODE. "
              "The PCB therefore connects each diode's cathode to the net the schematic gives its anode. See PCB review, finding R1.",
              "No title block (sheet title, revision, date, company) is present in the schematic.",
              "Value text of D1 and C1 overlap on the sheet (cosmetic).",
              "J5 is annotated 'keyed' but uses a plain header footprint.",
              "E-stop appears only as a loop (J3) in series with the coil supply; no E-stop status signal reaches the MCU header.",
              "No ADC measurement circuit, no USB, no 5 V rail and no test points are drawn."]:
        st.append(P("- " + t))
    K.build(path, st, "Schematic cover")


def schematic_tables_pdf(s, review, path):
    cov = [["Requested section", "Present on this PCB?", "Where", "Comment"],
           ["Power tree", "Yes", "Section 1 / power-tree page", "12 V in -> D3 -> +12V; no 5 V; 3V3 from Nucleo"],
           ["STM32 section", "Interface only", "J5", "STM32L476RG is on the external Nucleo module"],
           ["INA228 section", "Interface only", "J4", "INA228 is an external breakout; header carries 3V3/GND/SCL/SDA only. Shunt/VBUS wiring is off-board."],
           ["ADC measurement section", "NO", "-", "No ADC divider or ADC input on this PCB"],
           ["Temperature interface", "Yes", "U1, C2", "TC74A5-3.3VAT, I2C 0x4D"],
           ["UART / USB / Pi interface", "UART header only", "J6 (+ J5.6/J5.7)", "3.3 V UART; no USB connector"],
           ["Relay driver", "Yes", "Q1, R1, R2, D2, J2", "Low-side MOSFET, gate pull-down, flyback diode"],
           ["E-stop monitoring", "Loop only", "J3", "Opens coil supply in hardware; NO status line to the MCU"],
           ["Protection circuits", "Yes", "D3, D1, D2, C1", "Reverse-polarity Schottky, TVS, flyback, bulk cap (polarity issue R1)"]]
    shade = [(i, K.BAD) for i, r in enumerate(cov) if r[1] in ("NO", "Loop only")]
    nets = review["nets"]
    nrows = [["Net", "Pins"]] + [[n, ", ".join(f"{r}.{p}" for r, p in v)] for n, v in sorted(nets.items())]
    comps = [["Ref", "Value (as in schematic)", "Footprint"]] + [[x["ref"], x["value"], x["footprint"]] for x in sorted(s.symbols, key=lambda x: x["ref"])]
    st = [P("Section coverage against the requested schematic contents", H1), table(cov, [38 * mm, 28 * mm, 34 * mm, 80 * mm], shade=shade),
          P("Netlist (from the schematic)", H2), table(nrows, [30 * mm, 150 * mm]),
          P("Components (from the schematic)", H2), table(comps, [14 * mm, 70 * mm, 96 * mm], font=7)]
    K.build(path, st, "Schematic tables")


# ───────────────────────────── findings used by several documents ─────────────────────────────
ISSUES = [
    ("U1", "CRITICAL", "Diode polarity mismatch: D1 (TVS), D2 (flyback), D3 (reverse-polarity)",
     "Schematic symbols (OSBAMS:D_H, OSBAMS:D_TVS) have pin 1 = anode, pin 2 = cathode. The KiCad footprints used (D_DO-201AD, D_SMB) have pad 1 = cathode (square pad, silk 'K', band at pad 1). "
     "Because nets follow pin numbers, the PCB puts: D3 cathode on 12V_IN (blocks the supply), D2 cathode on COIL_SW (conducts from +12V to GND through Q1 when the gate is on), "
     "D1 cathode on GND (forward-conducts from +12V to GND once the rail is live). Assembled as drawn the board is dead at best and shorts the 12 V rail at worst.",
     "In KiCad: fix the symbol pin numbering (1 = K) or swap the footprints/nets, update the PCB from the schematic, re-run DRC/ERC, regenerate everything. Not changed here (task: do not modify the design)."),
    ("U2", "CRITICAL (scope)", "The PCB does not contain most of the requested 'controller PCB' functions",
     "The STM32L476RG (NUCLEO-L476RG) and INA228 (Adafruit breakout) are external plug-in modules, not on the board. There is no ADC measurement channel, no E-stop status input, no relay-feedback input, "
     "no USB, no 5 V rail/regulator, no programming header and no test points. The firmware in this repo expects PA0 (E-stop sense), PC9 (relay feedback via VO610A) and an independent ADC divider - none reach J5.",
     "Decide: (a) order this simple carrier board as it is, or (b) complete the Rev.2 controller design (STM32/INA228 on board or full interface header, ADC divider, E-stop/feedback sensing, 12->5 V, test points) before any turnkey order."),
    ("U3", "HIGH", "No authoritative KiCad export; DRC and ERC not run",
     "KiCad 10 / kicad-cli is not available in the build environment and no open library can read KiCad 10 files. Gerbers, drill, CPL and PDFs here are script-generated candidates. "
     "No DRC/ERC report exists in the repository.",
     "Run tools/mfg/export_with_kicad_cli.sh on a machine with KiCad 10; fix every DRC/ERC error; replace the candidate files."),
    ("U4", "HIGH", "BOM is incomplete",
     "No manufacturer/MPN in the design for: R1, R2, C2, C3, J1-J6 (headers and terminal blocks); D1/D2 have no manufacturer. 'No TBD components' cannot be met.",
     "Choose and approve MPNs for the red rows of the BOM; do not let the fab pick safety/measurement parts."),
    ("U5", "MEDIUM", "Silkscreen lacks connector names, polarity legends, revision, test points, fiducials",
     "Only reference designators and footprint outlines are on the silkscreen. No '+/-' on J1/J2/J3, no board name/revision, no fiducials, no test points.",
     "Add before release if desired (design change)."),
    ("U6", "MEDIUM", "Net-class track width not applied to power nets",
     "The project defines class 'Powerpath(12V/coil)' = 1.2 mm for +12V, COIL_SW, COIL_V, but every track is 0.3 mm (patterns have no leading '/', net names do). "
     "0.3 mm 1 oz copper is roughly a 1 A track; the coil current of the relay is not specified in the repo.",
     "Confirm the coil current from the relay datasheet; widen the tracks or fix the net-class patterns."),
    ("U7", "MEDIUM", "U1 (TC74 TO-220-5) annular ring 0.087 mm; finish unspecified",
     "Pads 1.275 x 1.8 mm with 1.1 mm drills leave 0.087 mm ring on the narrow axis (typical fab minimum 0.15 mm). Stackup says copper_finish 'None' - order options (HASL/ENIG, mask colour) are undefined.",
     "Ask PCBWay DFM; enlarge pads if rejected; choose the surface finish in the order."),
    ("U8", "MEDIUM", "Assembly mix: one SMT part, many through-hole parts",
     "Only D1 is SMT. PCBWay turnkey THT assembly is possible but costs more and needs the THT parts sourced; two TO-220 parts, axial resistors, terminal blocks and headers.",
     "Decide: SMT-only turnkey (D1) + customer THT, or full THT turnkey."),
    ("U9", "LOW", "Part-level questions",
     "TC74 variant: PCB uses TC74A5-3.3VAT (0x4D, 3.3 V) while the older repo BOM lists TC74A0-5.0VAT; J5 is 'keyed' in the schematic but the footprint is not; J6 uses a fan-header footprint; "
     "C1 is 25 V against a TVS clamp of about 24 V; D1/D2 manufacturer unnamed.",
     "Confirm and record decisions."),
    ("U10", "LOW", "Availability and obsolescence not checked; stale repo documents",
     "No network access to PCBWay/LCSC. Repo BOM spreadsheets (Hardware/OSBAMS_BOM.xlsx, Documentation/OSBAMS_BOM.xlsx, purchase list) describe an older design (Albright SW60, 'TBD' parts) and do not match this PCB; "
     "stray KiCad project files exist at the repo root; the project file's meta filename is stale.",
     "Check stock at order time; archive/refresh the old spreadsheets."),
]


def write_all(ctx, SUB, OUT):
    from . import docs_review
    docs_review.write_all(ctx, SUB, OUT, ISSUES)
