M48
; DRILL file KiCad 10.0.6 date 2026-10-01T09:09:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-01T09:09:59+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X193.995Y-79.11
X193.995Y-84.89
T2
X104.0Y-64.0
X104.0Y-146.0
X196.0Y-64.0
X196.0Y-146.0
M30
