"""Generate docs/rev2/6060B_COMMAND_EVIDENCE.md and BENCH_CHECKLIST.md from code."""
import os, sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
sys.path.insert(0, os.path.join(ROOT, "desktop"))

from equipment.drivers.keysight_6060b import commands as kc
from equipment import validation as v


def evidence_md() -> str:
    out = ["# 6060B command-evidence table", "",
           "Generated by `tools/gen_rev2_docs.py` from "
           "`desktop/equipment/drivers/keysight_6060b/commands.py`. Do not edit by hand.", "",
           "**Rule: a remote operation is enabled only if EVERY command it needs is VERIFIED.**", "",
           "Official sources:", f"- **{kc.PRG}** (covers 6060B/6063B and related loads)",
           f"- **{kc.OPM}**", "",
           "**Status today: nothing is VERIFIED.** The build environment's network policy blocks "
           "www.keysight.com, so neither manual could be read. Command strings below are *candidates*; "
           "'NOT LOCATED' means no section/page has been identified. Remote control is therefore blocked "
           "(and separately blocked by the unconfirmed GPIB interface).", "",
           "## Operations", "",
           "| operation | exact command(s) (candidate) | official document | section/page | verification status |",
           "|---|---|---|---|---|"]
    for op, cmd, doc, sec, st in kc.evidence_rows():
        out.append(f"| {op} | `{cmd}` | {doc} | {sec} | **{st}** |")
    out += ["", "## Individual commands", "",
            "| key | exact command (candidate) | official document | section/page | verification status | note |",
            "|---|---|---|---|---|---|"]
    for c in kc.COMMANDS.values():
        out.append(f"| {c.key} | `{c.template}` | {c.document} | {c.section} | **{c.status}** | {c.note} |")
    out += ["", "## To verify a command",
            "1. Find it in the programming manual (or operating manual for front-panel/local behaviour).",
            "2. Correct `template` if the syntax differs; fill `section` as `<section>, p.<n>`.",
            "3. Set `status=VERIFIED` in `commands.py`, rerun `python3 tools/gen_rev2_docs.py` and the tests.", ""]
    return "\n".join(out)


def checklist_md() -> str:
    out = ["# Bench checklist — exact physical tests, in order", "",
           "Generated by `tools/gen_rev2_docs.py` from `desktop/equipment/validation.py`. Do not edit by hand.", "",
           "Roles: **EDU36311A** low-energy commissioning source · **EDU34450A** reference DMM · "
           "**EDUX1052G** transient/shutdown observation · **AD2** low-voltage digital/protocol debugging · "
           "**6060B** the actual battery load (manual until GPIB is confirmed).", "",
           "Status of every step: **NOT_RUN**. Nothing here is BENCH_TESTED or HARDWARE_VALIDATED. "
           "Write each acceptance tolerance into the record *before* the run. "
           "Track results with `equipment.validation.ValidationLog` (PASS needs recorded data and the prerequisite steps PASS).", ""]
    phase = None
    for s in v.STEPS:
        if s.phase != phase:
            phase = s.phase
            out += ["", f"## {phase}", ""]
        out += [f"### {s.id} — {s.title}",
                f"- [ ] **Status:** NOT_RUN" + (f" · **Requires:** {s.blocked_by}" if s.blocked_by else ""),
                f"- **Equipment:** {s.equipment}",
                f"- **Procedure:** {s.procedure}",
                f"- **Pass criterion:** {s.pass_criterion}", ""]
    return "\n".join(out)


def main():
    d = os.path.join(ROOT, "docs", "rev2")
    for name, text in (("6060B_COMMAND_EVIDENCE.md", evidence_md()),
                       ("BENCH_CHECKLIST.md", checklist_md())):
        with open(os.path.join(d, name), "w") as f:
            f.write(text)
        print("wrote", name)


if __name__ == "__main__":
    main()
