"""Generate docs/rev2/6060B_DRIVER_EVIDENCE.md, BENCH_CHECKLIST.md and SFSU_EQUIPMENT_MATRIX.md from code."""
import os, sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
sys.path.insert(0, os.path.join(ROOT, "desktop"))

from equipment.drivers.keysight_6060b import commands as kc
from equipment import validation as v
from equipment import inventory as inv


def evidence_md() -> str:
    out = ["# 6060B driver evidence", "",
           "Generated by `tools/gen_rev2_docs.py` from "
           "`desktop/equipment/drivers/keysight_6060b/commands.py`. Do not edit by hand.", "",
           "**Rule: a remote operation is enabled only if EVERY command it needs is VERIFIED.**", "",
           "Official sources:", f"- **{kc.PRG}** (covers 6060B/6063B and related loads)",
           f"- **{kc.OPM}**", "",
           "**Status today: nothing is VERIFIED.** The build environment's network policy blocks "
           "www.keysight.com, so neither manual could be read. Command strings below are *candidates*; "
           "'NOT LOCATED' means no section/page has been identified. Remote control is therefore blocked "
           "(and separately blocked by the unconfirmed GPIB interface).", "",
           "Driver: `desktop/equipment/drivers/keysight_6060b/` (`Keysight6060B`). Each operation lists the commands it needs; "
           "`operation_enabled()` is true only when all are VERIFIED. Manual6060B and Simulator6060B need no SCPI and are the active modes. "
           "CC/CV/CR/transient are exposed only as far as the manuals document them.", "",
           "## Operations", "",
           "| operation | exact command(s) (candidate) | official document | section/page | verification status |",
           "|---|---|---|---|---|"]
    for op, cmd, doc, sec, st in kc.evidence_rows():
        out.append(f"| {op} | `{cmd}` | {doc} | {sec} | **{st}** |")
    out += ["", "## Individual commands", "",
            "| key | exact command (candidate) | official document | section/page | verification status | note |",
            "|---|---|---|---|---|---|"]
    for c in kc.COMMANDS.values():
        out.append(f"| {c.key} | `{c.template}` | {c.document} | {c.section} | **{c.status}** | {c.note} |")
    out += ["", "## To verify a command",
            "1. Find it in the programming manual (or operating manual for front-panel/local behaviour).",
            "2. Correct `template` if the syntax differs; fill `section` as `<section>, p.<n>`.",
            "3. Set `status=VERIFIED` in `commands.py`, rerun `python3 tools/gen_rev2_docs.py` and the tests.", ""]
    return "\n".join(out)


def checklist_md() -> str:
    out = ["# Bench checklist — exact physical tests, in order", "",
           "Generated by `tools/gen_rev2_docs.py` from `desktop/equipment/validation.py`. Do not edit by hand.", "",
           "Order: records → bench bring-up with no battery → pack connected, relay open, no load → first supervised low-current load → "
           "full characterization of the 36–42 V packs. Equipment: the **6060B** (the actual battery load, manual until GPIB is confirmed), "
           "the **EDU34450A** (reference measurement) and the **EDUX1052G** (validation-only observation), plus the OSBAMS stack itself. "
           "Status of every step: **NOT_RUN**. Nothing here is BENCH_TESTED or HARDWARE_VALIDATED. "
           "Write each acceptance tolerance into the record *before* the run. "
           "Track results with `equipment.validation.ValidationLog` (PASS needs recorded data and the prerequisite steps PASS).", ""]
    phase = None
    for s in v.STEPS:
        if s.phase != phase:
            phase = s.phase
            out += ["", f"## {phase}", ""]
        out += [f"### {s.id} — {s.title}" + (" *(optional)*" if s.optional else ""),
                f"- [ ] **Status:** NOT_RUN" + (f" · **Requires:** {s.blocked_by}" if s.blocked_by else ""),
                f"- **Equipment:** {s.equipment}",
                f"- **Procedure:** {s.procedure}",
                f"- **Pass criterion:** {s.pass_criterion}", ""]
    return "\n".join(out)


def matrix_md() -> str:
    out = ["# OSBAMS Rev.2 equipment stack", "",
           "Generated by `tools/gen_rev2_docs.py` from `desktop/equipment/inventory.py`. Do not edit by hand.", "",
           "Only equipment that is part of the Rev.2 system or its validation workflow is listed. "
           "Model and manufacturer are recorded; **serial number, asset ID and calibration status stay UNKNOWN until read off each instrument.**", "",
           "**Allowed current = min(battery profile limit, OSBAMS hardware limit, 6060B current limit, 300 W / battery voltage).**", "",
           "## Laboratory instruments", "",
           "| Instrument | Tier | Role | In automated loop | Envelope |", "|---|---|---|---|---|"]
    for i in inv.SFSU_EQUIPMENT.values():
        out.append(f"| {i.manufacturer} {i.model} | {i.tier} | {i.role} | "
                   f"{'yes' if i.in_automated_loop else 'no'} | {i.envelope} |")
    out.append("")
    for i in inv.SFSU_EQUIPMENT.values():
        out += [f"### {i.model} — {i.tier}",
                "- **Uses:** " + "; ".join(i.uses),
                "- **Limits:** " + "; ".join(i.limits),
                f"- **Interface:** {i.interface}",
                f"- **Serial / asset ID / calibration:** {i.serial_number} / {i.asset_id} / {i.calibration_status}", ""]
    out += ["## OSBAMS system", "", f"**{inv.PI_STM32_RULE}**", ""]
    for c in inv.SYSTEM_STACK.values():
        out += [f"### {c['name']} — {c['role']}", "- " + "\n- ".join(c["does"]), f"- *Status:* {c['status']}", ""]
    out += ["## Supported batteries (lithium-ion, ~10S, ~30–42 V)", "",
            "| Brand | Model | Nominal V | Max V | Ah | Wh |", "|---|---|---|---|---|---|"]
    for b in inv.SFSU_BATTERIES:
        out.append(f"| {b['brand']} | {b['model']} | {b['nominal_v']} | {b['max_v']} | {b['ah']} | {b['wh']} |")
    out += ["", "Connector: **XT60 = supported.** Connector type does not determine test capability — the validated power path does.",
            "", "## The physical story", "", "```",
            "lithium pack -> connector -> fuse -> disconnect -> relay -> shunt -> Agilent 6060B -> controlled discharge",
            "EDU34450A   -> independent reference measurements (calibration / verification only)",
            "EDUX1052G   -> relay / shutdown / transient observation (validation only)", "```", ""]
    return "\n".join(out)


def main():
    d = os.path.join(ROOT, "docs", "rev2")
    for name, text in (("6060B_DRIVER_EVIDENCE.md", evidence_md()),
                       ("BENCH_CHECKLIST.md", checklist_md()),
                       ("SFSU_EQUIPMENT_MATRIX.md", matrix_md())):
        with open(os.path.join(d, name), "w") as f:
            f.write(text)
        print("wrote", name)


if __name__ == "__main__":
    main()
