"""Single source for net classes, clearance rules and custom DRC rules (written into .kicad_pro / .kicad_dru).

Selected clearances (see docs: RC1.2 clearance review):
  * pack-level / Kelvin nets (up to the 44 V ceiling, <= ~77 V clamp):  PK_CLEARANCE mm
    IPC-2221B Table 6-1 (31-50 V and 51-100 V columns): B1 internal 0.1 mm, B4 external with permanent polymer coating (solder mask) 0.13 mm,
    B2 external uncoated 0.6 mm, A6 uncoated component terminations 0.6 mm. PK_CLEARANCE is >= 1.5x B4; exposed component pads and
    fine-pitch ICs are exempt by rule (the package pitch sets the gap, A6 cannot be met on a 0.5 mm-pitch IC).
  * host-side (USB/isolated) copper vs controller copper: ISO_CLEARANCE mm anywhere (3.0 mm in the ISO7721 area is geometric).
"""
PK_CLEARANCE = 0.2
ISO_CLEARANCE = 1.0

PK_NETS = {"PACK_INA", "PACK_INA_CON", "SHUNT_INP_CON", "SHUNT_INN_CON", "PACK_ADC", "ADC_MID", "RELAY_OUT", "FB_R1", "FB_R2",
           "SHUNT_INP_RAW", "SHUNT_INN_RAW", "INA_INP", "INA_INN", "INA_VBUS"}
KELVIN_NETS = {"INA_INP", "INA_INN"}
PWR_NETS = {"12V_RAW", "12V_F", "+12V", "COIL_V", "COIL_SW", "ESTOP_OUT", "3V3_HOST", "VBUS_USB", "BUCK_SW"}
RAIL_NETS = {"+3V3", "3V3_A"}
HOST_NETS = {"GND_HOST", "3V3_HOST", "VBUS_USB", "USB_DP", "USB_DM", "USB_DP_J", "USB_DM_J", "USB_CC1", "USB_CC2", "USB_SHIELD",
             "UART_RX_HOST", "UART_TX_HOST", "CP_VBUS_SENSE", "CP_RSTB"}

# name -> (clearance mm, track width mm, nets)
CLASSES = {
    "Default": (0.15, 0.2, set()),
    "POWER": (0.2, 0.3, PWR_NETS),
    "RAIL": (0.15, 0.3, RAIL_NETS),
    "PACKLEVEL": (PK_CLEARANCE, 0.2, PK_NETS - KELVIN_NETS),
    "KELVIN": (PK_CLEARANCE, 0.2, KELVIN_NETS),
    "HOST": (0.15, 0.2, HOST_NETS),
}


def pro_net_settings():
    return {"meta": {"version": 4},
            "classes": [dict(name=n, clearance=c, track_width=w, via_diameter=0.6, via_drill=0.3) for n, (c, w, _) in CLASSES.items()],
            "netclass_patterns": [dict(netclass=n, pattern=net) for n, (_, _, nets) in CLASSES.items() for net in sorted(nets)]}


def dru_text():
    return f"""(version 1)
# OSBAMS Rev.2 custom DRC rules (generated by design/netclasses.py)
# 1. isolation: host-side copper vs controller-side copper
(rule "isolation_host_to_controller"
  (condition "A.hasNetclass('HOST') && B.NetName != '' && !B.hasNetclass('HOST')")
  (constraint clearance (min {ISO_CLEARANCE}mm)))
(rule "isolation_controller_to_host"
  (condition "B.hasNetclass('HOST') && A.NetName != '' && !A.hasNetclass('HOST')")
  (constraint clearance (min {ISO_CLEARANCE}mm)))
# 2. fine-pitch exemption: inside the INA228 courtyard (0.5 mm pitch, 0.15 mm pad gap set by the package) the pack-level class is relaxed to the board minimum
(rule "fine_pitch_ina228"
  (condition "(A.insideCourtyard('U2') || B.insideCourtyard('U2')) && (A.hasNetclass('PACKLEVEL') || A.hasNetclass('KELVIN') || B.hasNetclass('PACKLEVEL') || B.hasNetclass('KELVIN'))")
  (constraint clearance (min 0.15mm)))
"""
